// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubSystemAccount_custom.h file.

#include "server/SystemAccount.h"
#include "stubSystemAccount_custom.h"

#ifndef STUB_SERVER_SYSTEMACCOUNT_H
#define STUB_SERVER_SYSTEMACCOUNT_H

#ifndef STUB_SystemAccount_SystemAccount
//#define STUB_SystemAccount_SystemAccount
   SystemAccount::SystemAccount(Connection * conn, const std::string & username, const std::string & passwd, const std::string & id, long intId)
    : Admin(conn, username, passwd, id, intId)
  {
    
  }
#endif //STUB_SystemAccount_SystemAccount

#ifndef STUB_SystemAccount_SystemAccount_DTOR
//#define STUB_SystemAccount_SystemAccount_DTOR
   SystemAccount::~SystemAccount()
  {
    
  }
#endif //STUB_SystemAccount_SystemAccount_DTOR

#ifndef STUB_SystemAccount_getType
//#define STUB_SystemAccount_getType
  const char* SystemAccount::getType() const
  {
    return nullptr;
  }
#endif //STUB_SystemAccount_getType

#ifndef STUB_SystemAccount_isPersisted
//#define STUB_SystemAccount_isPersisted
  bool SystemAccount::isPersisted() const
  {
    return false;
  }
#endif //STUB_SystemAccount_isPersisted


#endif