// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubRuleHandler_custom.h file.

#ifndef STUB_SERVER_RULEHANDLER_H
#define STUB_SERVER_RULEHANDLER_H

#include "server/RuleHandler.h"
#include "stubRuleHandler_custom.h"

#ifndef STUB_RuleHandler_check
//#define STUB_RuleHandler_check
  int RuleHandler::check(const Atlas::Objects::Root & desc)
  {
    return 0;
  }
#endif //STUB_RuleHandler_check

#ifndef STUB_RuleHandler_install
//#define STUB_RuleHandler_install
  int RuleHandler::install(const std::string &, const std::string &, const Atlas::Objects::Root & desc, std::string &, std::string &, std::map<const TypeNode*, TypeNode::PropertiesUpdate>& changes)
  {
    return 0;
  }
#endif //STUB_RuleHandler_install

#ifndef STUB_RuleHandler_update
//#define STUB_RuleHandler_update
  int RuleHandler::update(const std::string &, const Atlas::Objects::Root & desc, std::map<const TypeNode*, TypeNode::PropertiesUpdate>& changes)
  {
    return 0;
  }
#endif //STUB_RuleHandler_update


#endif