// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubMaster_custom.h file.

#include "server/Master.h"
#include "stubMaster_custom.h"

#ifndef STUB_SERVER_MASTER_H
#define STUB_SERVER_MASTER_H

#ifndef STUB_Master_Master
//#define STUB_Master_Master
   Master::Master(ServerRouting & svr, const std::string & id)
    : Router(svr, id)
  {
    
  }
#endif //STUB_Master_Master

#ifndef STUB_Master_Master_DTOR
//#define STUB_Master_Master_DTOR
   Master::~Master()
  {
    
  }
#endif //STUB_Master_Master_DTOR

#ifndef STUB_Master_operation
//#define STUB_Master_operation
  void Master::operation(const Operation &, OpVector &)
  {
    
  }
#endif //STUB_Master_operation


#endif