// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubEntityFactory_impl_custom.h file.

#include "server/EntityFactory_impl.h"
#include "stubEntityFactory_impl_custom.h"

#ifndef STUB_SERVER_ENTITYFACTORY_IMPL_H
#define STUB_SERVER_ENTITYFACTORY_IMPL_H

#endif