// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubMindInspector_custom.h file.

#include "server/MindInspector.h"
#include "stubMindInspector_custom.h"

#ifndef STUB_SERVER_MINDINSPECTOR_H
#define STUB_SERVER_MINDINSPECTOR_H

#ifndef STUB_MindInspector_MindInspector
//#define STUB_MindInspector_MindInspector
   MindInspector::MindInspector()
    : sigc::trackable()
  {
    
  }
#endif //STUB_MindInspector_MindInspector

#ifndef STUB_MindInspector_MindInspector_DTOR
//#define STUB_MindInspector_MindInspector_DTOR
   MindInspector::~MindInspector()
  {
    
  }
#endif //STUB_MindInspector_MindInspector_DTOR

#ifndef STUB_MindInspector_queryEntityForThoughts
//#define STUB_MindInspector_queryEntityForThoughts
  void MindInspector::queryEntityForThoughts(const std::string& entityId)
  {
    
  }
#endif //STUB_MindInspector_queryEntityForThoughts

#ifndef STUB_MindInspector_relayResponseReceived
//#define STUB_MindInspector_relayResponseReceived
  void MindInspector::relayResponseReceived(const Operation& op, const std::string& entityId)
  {
    
  }
#endif //STUB_MindInspector_relayResponseReceived


#endif