// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubTypeUpdateCoordinator_custom.h file.

#ifndef STUB_SERVER_TYPEUPDATECOORDINATOR_H
#define STUB_SERVER_TYPEUPDATECOORDINATOR_H

#include "server/TypeUpdateCoordinator.h"
#include "stubTypeUpdateCoordinator_custom.h"

#ifndef STUB_TypeUpdateCoordinator_TypeUpdateCoordinator
//#define STUB_TypeUpdateCoordinator_TypeUpdateCoordinator
   TypeUpdateCoordinator::TypeUpdateCoordinator(Inheritance& inheritance, WorldRouter& worldRouter, ServerRouting& serverRouting)
  {
    
  }
#endif //STUB_TypeUpdateCoordinator_TypeUpdateCoordinator


#endif