// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubSpawnEntity_custom.h file.

#include "server/SpawnEntity.h"
#include "stubSpawnEntity_custom.h"

#ifndef STUB_SERVER_SPAWNENTITY_H
#define STUB_SERVER_SPAWNENTITY_H

#ifndef STUB_SpawnEntity_SpawnEntity
//#define STUB_SpawnEntity_SpawnEntity
   SpawnEntity::SpawnEntity(LocatedEntity * e)
    : Spawn(e)
  {
    
  }
#endif //STUB_SpawnEntity_SpawnEntity

#ifndef STUB_SpawnEntity_setup
//#define STUB_SpawnEntity_setup
  int SpawnEntity::setup(const Atlas::Message::MapType & data)
  {
    return 0;
  }
#endif //STUB_SpawnEntity_setup

#ifndef STUB_SpawnEntity_spawnEntity
//#define STUB_SpawnEntity_spawnEntity
  int SpawnEntity::spawnEntity(const std::string & type, const Atlas::Objects::Entity::RootEntity & dsc) const
  {
    return 0;
  }
#endif //STUB_SpawnEntity_spawnEntity

#ifndef STUB_SpawnEntity_addToMessage
//#define STUB_SpawnEntity_addToMessage
  int SpawnEntity::addToMessage(Atlas::Message::MapType & msg) const
  {
    return 0;
  }
#endif //STUB_SpawnEntity_addToMessage

#ifndef STUB_SpawnEntity_placeInSpawn
//#define STUB_SpawnEntity_placeInSpawn
  int SpawnEntity::placeInSpawn(Location& location) const
  {
    return 0;
  }
#endif //STUB_SpawnEntity_placeInSpawn


#endif