// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubAdmin_custom.h file.

#include "server/Admin.h"
#include "stubAdmin_custom.h"

#ifndef STUB_SERVER_ADMIN_H
#define STUB_SERVER_ADMIN_H

#ifndef STUB_Admin_createCharacterEntity
//#define STUB_Admin_createCharacterEntity
  LocatedEntity* Admin::createCharacterEntity(const std::string &, const Atlas::Objects::Entity::RootEntity &, const Atlas::Objects::Root &)
  {
    return nullptr;
  }
#endif //STUB_Admin_createCharacterEntity

#ifndef STUB_Admin_characterError
//#define STUB_Admin_characterError
  int Admin::characterError(const Operation & op, const Atlas::Objects::Root & ent, OpVector & res) const
  {
    return 0;
  }
#endif //STUB_Admin_characterError

#ifndef STUB_Admin_createObject
//#define STUB_Admin_createObject
  void Admin::createObject(const std::string &, const Atlas::Objects::Root &, const Operation &, OpVector &)
  {
    
  }
#endif //STUB_Admin_createObject

#ifndef STUB_Admin_opDispatched
//#define STUB_Admin_opDispatched
  void Admin::opDispatched(Operation op)
  {
    
  }
#endif //STUB_Admin_opDispatched

#ifndef STUB_Admin_setAttribute
//#define STUB_Admin_setAttribute
  void Admin::setAttribute(const Atlas::Objects::Root& arg)
  {
    
  }
#endif //STUB_Admin_setAttribute

#ifndef STUB_Admin_Admin
//#define STUB_Admin_Admin
   Admin::Admin(Connection * conn, const std::string & username, const std::string & passwd, const std::string & id, long intId)
    : Account(conn, username, passwd, id, intId)
  {
    
  }
#endif //STUB_Admin_Admin

#ifndef STUB_Admin_Admin_DTOR
//#define STUB_Admin_Admin_DTOR
   Admin::~Admin()
  {
    
  }
#endif //STUB_Admin_Admin_DTOR

#ifndef STUB_Admin_getType
//#define STUB_Admin_getType
  const char* Admin::getType() const
  {
    return nullptr;
  }
#endif //STUB_Admin_getType

#ifndef STUB_Admin_addToMessage
//#define STUB_Admin_addToMessage
  void Admin::addToMessage(Atlas::Message::MapType &) const
  {
    
  }
#endif //STUB_Admin_addToMessage

#ifndef STUB_Admin_addToEntity
//#define STUB_Admin_addToEntity
  void Admin::addToEntity(const Atlas::Objects::Entity::RootEntity &) const
  {
    
  }
#endif //STUB_Admin_addToEntity

#ifndef STUB_Admin_LogoutOperation
//#define STUB_Admin_LogoutOperation
  void Admin::LogoutOperation(const Operation &, OpVector &)
  {
    
  }
#endif //STUB_Admin_LogoutOperation

#ifndef STUB_Admin_GetOperation
//#define STUB_Admin_GetOperation
  void Admin::GetOperation(const Operation &, OpVector &)
  {
    
  }
#endif //STUB_Admin_GetOperation

#ifndef STUB_Admin_SetOperation
//#define STUB_Admin_SetOperation
  void Admin::SetOperation(const Operation &, OpVector &)
  {
    
  }
#endif //STUB_Admin_SetOperation

#ifndef STUB_Admin_OtherOperation
//#define STUB_Admin_OtherOperation
  void Admin::OtherOperation(const Operation &, OpVector &)
  {
    
  }
#endif //STUB_Admin_OtherOperation

#ifndef STUB_Admin_customMonitorOperation
//#define STUB_Admin_customMonitorOperation
  void Admin::customMonitorOperation(const Operation &, OpVector &)
  {
    
  }
#endif //STUB_Admin_customMonitorOperation


#endif