// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubRuleset_custom.h file.

#ifndef STUB_SERVER_RULESET_H
#define STUB_SERVER_RULESET_H

#include "server/Ruleset.h"
#include "stubRuleset_custom.h"


#ifndef STUB_Ruleset_installItem
//#define STUB_Ruleset_installItem
  void Ruleset::installItem(const std::string& class_name, const Atlas::Objects::Root& class_desc, std::map<const TypeNode*, TypeNode::PropertiesUpdate>& changes)
  {
    
  }
#endif //STUB_Ruleset_installItem

#ifndef STUB_Ruleset_installRuleInner
//#define STUB_Ruleset_installRuleInner
  int Ruleset::installRuleInner(const std::string& class_name, const Atlas::Objects::Root& class_desc, std::string& dependent, std::string& reason, std::map<const TypeNode*, TypeNode::PropertiesUpdate>& changes)
  {
    return 0;
  }
#endif //STUB_Ruleset_installRuleInner

#ifndef STUB_Ruleset_modifyRuleInner
//#define STUB_Ruleset_modifyRuleInner
  int Ruleset::modifyRuleInner(const std::string& class_name, const Atlas::Objects::Root& class_desc, std::map<const TypeNode*, TypeNode::PropertiesUpdate>& changes)
  {
    return 0;
  }
#endif //STUB_Ruleset_modifyRuleInner

#ifndef STUB_Ruleset_getRulesFromFiles
//#define STUB_Ruleset_getRulesFromFiles
  void Ruleset::getRulesFromFiles(boost::filesystem::path directory, std::map<std::string, Atlas::Objects::Root>&)
  {
    
  }
#endif //STUB_Ruleset_getRulesFromFiles

#ifndef STUB_Ruleset_waitForRule
//#define STUB_Ruleset_waitForRule
  void Ruleset::waitForRule(const std::string& class_name, const Atlas::Objects::Root& class_desc, const std::string& dependent, const std::string& reason)
  {
    
  }
#endif //STUB_Ruleset_waitForRule

#ifndef STUB_Ruleset_processChangedRules
//#define STUB_Ruleset_processChangedRules
  void Ruleset::processChangedRules()
  {
    
  }
#endif //STUB_Ruleset_processChangedRules

#ifndef STUB_Ruleset_Ruleset
//#define STUB_Ruleset_Ruleset
   Ruleset::Ruleset(EntityBuilder& eb, boost::asio::io_context& io_context, PropertyManager& propertyManager)
    : Singleton(eb, io_context, propertyManager)
  {
    
  }
#endif //STUB_Ruleset_Ruleset

#ifndef STUB_Ruleset_Ruleset_DTOR
//#define STUB_Ruleset_Ruleset_DTOR
   Ruleset::~Ruleset()
  {
    
  }
#endif //STUB_Ruleset_Ruleset_DTOR

#ifndef STUB_Ruleset_loadRules
//#define STUB_Ruleset_loadRules
  void Ruleset::loadRules(const std::string&)
  {
    
  }
#endif //STUB_Ruleset_loadRules

#ifndef STUB_Ruleset_installRule
//#define STUB_Ruleset_installRule
  int Ruleset::installRule(const std::string& class_name, const std::string& section, const Atlas::Objects::Root& class_desc)
  {
    return 0;
  }
#endif //STUB_Ruleset_installRule

#ifndef STUB_Ruleset_modifyRule
//#define STUB_Ruleset_modifyRule
  int Ruleset::modifyRule(const std::string& class_name, const Atlas::Objects::Root& class_desc)
  {
    return 0;
  }
#endif //STUB_Ruleset_modifyRule


#endif