// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCommAsioListener_impl_custom.h file.

#include "server/CommAsioListener_impl.h"
#include "stubCommAsioListener_impl_custom.h"

#ifndef STUB_SERVER_COMMASIOLISTENER_IMPL_H
#define STUB_SERVER_COMMASIOLISTENER_IMPL_H

#endif