// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_Element_custom.h file.

#ifndef STUB_RULESETS_PYTHON_CYPY_ELEMENT_H
#define STUB_RULESETS_PYTHON_CYPY_ELEMENT_H

#include "rulesets/python/CyPy_Element.h"
#include "stubCyPy_Element_custom.h"

#ifndef STUB_CyPy_Element_CyPy_Element
//#define STUB_CyPy_Element_CyPy_Element
   CyPy_Element::CyPy_Element(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : WrapperBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_Element_CyPy_Element

#ifndef STUB_CyPy_Element_CyPy_Element
//#define STUB_CyPy_Element_CyPy_Element
   CyPy_Element::CyPy_Element(Py::PythonClassInstance* self, Atlas::Message::Element element)
    : WrapperBase(self, element)
  {
    
  }
#endif //STUB_CyPy_Element_CyPy_Element

#ifndef STUB_CyPy_Element_init_type
//#define STUB_CyPy_Element_init_type
   void CyPy_Element::init_type()
  {
    
  }
#endif //STUB_CyPy_Element_init_type

#ifndef STUB_CyPy_Element_wrap
//#define STUB_CyPy_Element_wrap
   Py::Object CyPy_Element::wrap(Atlas::Message::Element value)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_wrap

#ifndef STUB_CyPy_Element_repr
//#define STUB_CyPy_Element_repr
  Py::Object CyPy_Element::repr()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_repr

#ifndef STUB_CyPy_Element_getattro
//#define STUB_CyPy_Element_getattro
  Py::Object CyPy_Element::getattro(const Py::String&)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_getattro

#ifndef STUB_CyPy_Element_setattro
//#define STUB_CyPy_Element_setattro
  int CyPy_Element::setattro(const Py::String& name, const Py::Object& attr)
  {
    return 0;
  }
#endif //STUB_CyPy_Element_setattro

#ifndef STUB_CyPy_Element_get_name
//#define STUB_CyPy_Element_get_name
  Py::Object CyPy_Element::get_name()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_get_name

#ifndef STUB_CyPy_Element_pythonize
//#define STUB_CyPy_Element_pythonize
  Py::Object CyPy_Element::pythonize()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_pythonize

#ifndef STUB_CyPy_Element_asPyObject
//#define STUB_CyPy_Element_asPyObject
   Py::Object CyPy_Element::asPyObject(const Atlas::Message::Element& obj)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_asPyObject

#ifndef STUB_CyPy_Element_asElement
//#define STUB_CyPy_Element_asElement
   Atlas::Message::Element CyPy_Element::asElement(const Py::Object& o)
  {
    return *static_cast< Atlas::Message::Element*>(nullptr);
  }
#endif //STUB_CyPy_Element_asElement

#ifndef STUB_CyPy_Element_mapAsPyObject
//#define STUB_CyPy_Element_mapAsPyObject
   Py::Object CyPy_Element::mapAsPyObject(const Atlas::Message::MapType& map)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_mapAsPyObject

#ifndef STUB_CyPy_Element_listAsPyObject
//#define STUB_CyPy_Element_listAsPyObject
   Py::Object CyPy_Element::listAsPyObject(const Atlas::Message::ListType& list)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_listAsPyObject

#ifndef STUB_CyPy_Element_listAsElement
//#define STUB_CyPy_Element_listAsElement
   Atlas::Message::ListType CyPy_Element::listAsElement(const Py::List& list)
  {
    return *static_cast< Atlas::Message::ListType*>(nullptr);
  }
#endif //STUB_CyPy_Element_listAsElement

#ifndef STUB_CyPy_Element_dictAsElement
//#define STUB_CyPy_Element_dictAsElement
   Atlas::Message::MapType CyPy_Element::dictAsElement(const Py::Dict& dict)
  {
    return *static_cast< Atlas::Message::MapType*>(nullptr);
  }
#endif //STUB_CyPy_Element_dictAsElement

#ifndef STUB_CyPy_Element_rich_compare
//#define STUB_CyPy_Element_rich_compare
  Py::Object CyPy_Element::rich_compare(const Py::Object& other, int op)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_rich_compare


#endif