// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_Character_custom.h file.

#ifndef STUB_RULESETS_PYTHON_CYPY_CHARACTER_H
#define STUB_RULESETS_PYTHON_CYPY_CHARACTER_H

#include "rulesets/python/CyPy_Character.h"
#include "stubCyPy_Character_custom.h"

#ifndef STUB_CyPy_Character_CyPy_Character
//#define STUB_CyPy_Character_CyPy_Character
   CyPy_Character::CyPy_Character(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : CyPy_LocatedEntityBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_Character_CyPy_Character

#ifndef STUB_CyPy_Character_CyPy_Character
//#define STUB_CyPy_Character_CyPy_Character
   CyPy_Character::CyPy_Character(Py::PythonClassInstance* self, Ref<Character> value)
    : CyPy_LocatedEntityBase(self, value)
  {
    
  }
#endif //STUB_CyPy_Character_CyPy_Character

#ifndef STUB_CyPy_Character_CyPy_Character_DTOR
//#define STUB_CyPy_Character_CyPy_Character_DTOR
   CyPy_Character::~CyPy_Character()
  {
    
  }
#endif //STUB_CyPy_Character_CyPy_Character_DTOR

#ifndef STUB_CyPy_Character_init_type
//#define STUB_CyPy_Character_init_type
   void CyPy_Character::init_type()
  {
    
  }
#endif //STUB_CyPy_Character_init_type

#ifndef STUB_CyPy_Character_start_task
//#define STUB_CyPy_Character_start_task
  Py::Object CyPy_Character::start_task(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Character_start_task

#ifndef STUB_CyPy_Character_mind2body
//#define STUB_CyPy_Character_mind2body
  Py::Object CyPy_Character::mind2body(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Character_mind2body

#ifndef STUB_CyPy_Character_send_world
//#define STUB_CyPy_Character_send_world
  Py::Object CyPy_Character::send_world(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Character_send_world


#endif