// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_BaseMind_custom.h file.

#ifndef STUB_RULESETS_PYTHON_CYPY_BASEMIND_H
#define STUB_RULESETS_PYTHON_CYPY_BASEMIND_H

#include "rulesets/python/CyPy_BaseMind.h"
#include "stubCyPy_BaseMind_custom.h"

#ifndef STUB_CyPy_BaseMind_CyPy_BaseMind
//#define STUB_CyPy_BaseMind_CyPy_BaseMind
   CyPy_BaseMind::CyPy_BaseMind(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : CyPy_LocatedEntityBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_BaseMind_CyPy_BaseMind

#ifndef STUB_CyPy_BaseMind_CyPy_BaseMind
//#define STUB_CyPy_BaseMind_CyPy_BaseMind
   CyPy_BaseMind::CyPy_BaseMind(Py::PythonClassInstance* self, Ref<BaseMind> value)
    : CyPy_LocatedEntityBase(self, value)
  {
    
  }
#endif //STUB_CyPy_BaseMind_CyPy_BaseMind

#ifndef STUB_CyPy_BaseMind_CyPy_BaseMind_DTOR
//#define STUB_CyPy_BaseMind_CyPy_BaseMind_DTOR
   CyPy_BaseMind::~CyPy_BaseMind()
  {
    
  }
#endif //STUB_CyPy_BaseMind_CyPy_BaseMind_DTOR

#ifndef STUB_CyPy_BaseMind_init_type
//#define STUB_CyPy_BaseMind_init_type
   void CyPy_BaseMind::init_type()
  {
    
  }
#endif //STUB_CyPy_BaseMind_init_type

#ifndef STUB_CyPy_BaseMind_getattro
//#define STUB_CyPy_BaseMind_getattro
  Py::Object CyPy_BaseMind::getattro(const Py::String&)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_BaseMind_getattro

#ifndef STUB_CyPy_BaseMind_setattro
//#define STUB_CyPy_BaseMind_setattro
  int CyPy_BaseMind::setattro(const Py::String& name, const Py::Object& attr)
  {
    return 0;
  }
#endif //STUB_CyPy_BaseMind_setattro

#ifndef STUB_CyPy_BaseMind_refreshPath
//#define STUB_CyPy_BaseMind_refreshPath
  Py::Object CyPy_BaseMind::refreshPath()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_BaseMind_refreshPath

#ifndef STUB_CyPy_BaseMind_setDestination
//#define STUB_CyPy_BaseMind_setDestination
  Py::Object CyPy_BaseMind::setDestination(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_BaseMind_setDestination


#endif