// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPoint3Property_custom.h file.

#ifndef STUB_RULES_POINT3PROPERTY_H
#define STUB_RULES_POINT3PROPERTY_H

#include "rules/Point3Property.h"
#include "stubPoint3Property_custom.h"

#ifndef STUB_Point3Property_Point3Property
//#define STUB_Point3Property_Point3Property
   Point3Property::Point3Property(const Point3Property& rhs)
    : PropertyBase(rhs)
  {
    
  }
#endif //STUB_Point3Property_Point3Property

#ifndef STUB_Point3Property_get
//#define STUB_Point3Property_get
  int Point3Property::get(Atlas::Message::Element& val) const
  {
    return 0;
  }
#endif //STUB_Point3Property_get

#ifndef STUB_Point3Property_set
//#define STUB_Point3Property_set
  void Point3Property::set(const Atlas::Message::Element&)
  {
    
  }
#endif //STUB_Point3Property_set

#ifndef STUB_Point3Property_add
//#define STUB_Point3Property_add
  void Point3Property::add(const std::string & key, const Atlas::Objects::Entity::RootEntity & ent) const
  {
    
  }
#endif //STUB_Point3Property_add

#ifndef STUB_Point3Property_copy
//#define STUB_Point3Property_copy
  Point3Property* Point3Property::copy() const
  {
    return nullptr;
  }
#endif //STUB_Point3Property_copy


#endif