// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubModifier_custom.h file.

#ifndef STUB_RULES_MODIFIER_H
#define STUB_RULES_MODIFIER_H

#include "rules/Modifier.h"
#include "stubModifier_custom.h"

#ifndef STUB_Modifier_process
//#define STUB_Modifier_process
  void Modifier::process(Atlas::Message::Element& element, const Atlas::Message::Element& baseValue) const
  {
    
  }
#endif //STUB_Modifier_process

#ifndef STUB_Modifier_getType
//#define STUB_Modifier_getType
  ModifierType Modifier::getType() const
  {
    return *static_cast<ModifierType*>(nullptr);
  }
#endif //STUB_Modifier_getType

#ifndef STUB_Modifier_createModifier
//#define STUB_Modifier_createModifier
   std::unique_ptr<Modifier> Modifier::createModifier(ModifierType modificationType, Atlas::Message::Element attr)
  {
    return *static_cast< std::unique_ptr<Modifier>*>(nullptr);
  }
#endif //STUB_Modifier_createModifier


#ifndef STUB_DefaultModifier_process
//#define STUB_DefaultModifier_process
  void DefaultModifier::process(Atlas::Message::Element& element, const Atlas::Message::Element& baseValue) const
  {
    
  }
#endif //STUB_DefaultModifier_process


#ifndef STUB_PrependModifier_process
//#define STUB_PrependModifier_process
  void PrependModifier::process(Atlas::Message::Element& element, const Atlas::Message::Element& baseValue) const
  {
    
  }
#endif //STUB_PrependModifier_process


#ifndef STUB_AppendModifier_process
//#define STUB_AppendModifier_process
  void AppendModifier::process(Atlas::Message::Element& element, const Atlas::Message::Element& baseValue) const
  {
    
  }
#endif //STUB_AppendModifier_process


#ifndef STUB_SubtractModifier_process
//#define STUB_SubtractModifier_process
  void SubtractModifier::process(Atlas::Message::Element& element, const Atlas::Message::Element& baseValue) const
  {
    
  }
#endif //STUB_SubtractModifier_process


#ifndef STUB_AddFractionModifier_process
//#define STUB_AddFractionModifier_process
  void AddFractionModifier::process(Atlas::Message::Element& element, const Atlas::Message::Element& baseValue) const
  {
    
  }
#endif //STUB_AddFractionModifier_process


#endif