// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubSimpleTypeStore_custom.h file.

#ifndef STUB_RULES_SIMPLETYPESTORE_H
#define STUB_RULES_SIMPLETYPESTORE_H

#include "rules/SimpleTypeStore.h"
#include "stubSimpleTypeStore_custom.h"

#ifndef STUB_SimpleTypeStore_SimpleTypeStore
//#define STUB_SimpleTypeStore_SimpleTypeStore
   SimpleTypeStore::SimpleTypeStore()
    : TypeStore()
  {
    
  }
#endif //STUB_SimpleTypeStore_SimpleTypeStore

#ifndef STUB_SimpleTypeStore_getType
//#define STUB_SimpleTypeStore_getType
  const TypeNode* SimpleTypeStore::getType(const std::string& parent) const
  {
    return nullptr;
  }
#endif //STUB_SimpleTypeStore_getType

#ifndef STUB_SimpleTypeStore_addChild
//#define STUB_SimpleTypeStore_addChild
  TypeNode* SimpleTypeStore::addChild(const Atlas::Objects::Root& obj)
  {
    return nullptr;
  }
#endif //STUB_SimpleTypeStore_addChild

#ifndef STUB_SimpleTypeStore_readAttributesIntoType
//#define STUB_SimpleTypeStore_readAttributesIntoType
  void SimpleTypeStore::readAttributesIntoType(TypeNode& type, const Atlas::Objects::Root& obj)
  {
    
  }
#endif //STUB_SimpleTypeStore_readAttributesIntoType


#endif