// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubSimpleProperty_custom.h file.

#ifndef STUB_RULES_SIMPLEPROPERTY_H
#define STUB_RULES_SIMPLEPROPERTY_H

#include "rules/SimpleProperty.h"
#include "stubSimpleProperty_custom.h"

#ifndef STUB_SimpleProperty_copy
//#define STUB_SimpleProperty_copy
  SimpleProperty* SimpleProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_SimpleProperty_copy

#ifndef STUB_SimpleProperty_apply
//#define STUB_SimpleProperty_apply
  void SimpleProperty::apply(LocatedEntity *)
  {
    
  }
#endif //STUB_SimpleProperty_apply


#endif