// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubModifierType_custom.h file.

#ifndef STUB_RULES_MODIFIERTYPE_H
#define STUB_RULES_MODIFIERTYPE_H

#include "rules/ModifierType.h"
#include "stubModifierType_custom.h"

#endif