// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_TerrainProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_PYTHON_CYPY_TERRAINPROPERTY_H
#define STUB_RULES_SIMULATION_PYTHON_CYPY_TERRAINPROPERTY_H

#include "rules/simulation/python/CyPy_TerrainProperty.h"
#include "stubCyPy_TerrainProperty_custom.h"

#ifndef STUB_CyPy_TerrainProperty_CyPy_TerrainProperty
//#define STUB_CyPy_TerrainProperty_CyPy_TerrainProperty
   CyPy_TerrainProperty::CyPy_TerrainProperty(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : WrapperBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_TerrainProperty_CyPy_TerrainProperty

#ifndef STUB_CyPy_TerrainProperty_CyPy_TerrainProperty
//#define STUB_CyPy_TerrainProperty_CyPy_TerrainProperty
   CyPy_TerrainProperty::CyPy_TerrainProperty(Py::PythonClassInstance* self, Ref<LocatedEntity> value)
    : WrapperBase(self, value)
  {
    
  }
#endif //STUB_CyPy_TerrainProperty_CyPy_TerrainProperty

#ifndef STUB_CyPy_TerrainProperty_CyPy_TerrainProperty_DTOR
//#define STUB_CyPy_TerrainProperty_CyPy_TerrainProperty_DTOR
   CyPy_TerrainProperty::~CyPy_TerrainProperty()
  {
    
  }
#endif //STUB_CyPy_TerrainProperty_CyPy_TerrainProperty_DTOR

#ifndef STUB_CyPy_TerrainProperty_init_type
//#define STUB_CyPy_TerrainProperty_init_type
   void CyPy_TerrainProperty::init_type()
  {
    
  }
#endif //STUB_CyPy_TerrainProperty_init_type

#ifndef STUB_CyPy_TerrainProperty_getTerrainProperty
//#define STUB_CyPy_TerrainProperty_getTerrainProperty
  const TerrainProperty& CyPy_TerrainProperty::getTerrainProperty()
  {
    return *static_cast<const TerrainProperty*>(nullptr);
  }
#endif //STUB_CyPy_TerrainProperty_getTerrainProperty

#ifndef STUB_CyPy_TerrainProperty_getHeight
//#define STUB_CyPy_TerrainProperty_getHeight
  Py::Object CyPy_TerrainProperty::getHeight(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_TerrainProperty_getHeight

#ifndef STUB_CyPy_TerrainProperty_getSurface
//#define STUB_CyPy_TerrainProperty_getSurface
  Py::Object CyPy_TerrainProperty::getSurface(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_TerrainProperty_getSurface

#ifndef STUB_CyPy_TerrainProperty_getSurfaceName
//#define STUB_CyPy_TerrainProperty_getSurfaceName
  Py::Object CyPy_TerrainProperty::getSurfaceName(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_TerrainProperty_getSurfaceName

#ifndef STUB_CyPy_TerrainProperty_getNormal
//#define STUB_CyPy_TerrainProperty_getNormal
  Py::Object CyPy_TerrainProperty::getNormal(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_TerrainProperty_getNormal

#ifndef STUB_CyPy_TerrainProperty_findMods
//#define STUB_CyPy_TerrainProperty_findMods
  Py::Object CyPy_TerrainProperty::findMods(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_TerrainProperty_findMods


#endif