// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_Entity_custom.h file.

#ifndef STUB_RULES_SIMULATION_PYTHON_CYPY_ENTITY_H
#define STUB_RULES_SIMULATION_PYTHON_CYPY_ENTITY_H

#include "rules/simulation/python/CyPy_Entity.h"
#include "stubCyPy_Entity_custom.h"

#ifndef STUB_CyPy_Entity_CyPy_Entity
//#define STUB_CyPy_Entity_CyPy_Entity
   CyPy_Entity::CyPy_Entity(Py::PythonClassInstanceWeak* self, Py::Tuple& args, Py::Dict& kwds)
    : CyPy_LocatedEntityBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_Entity_CyPy_Entity

#ifndef STUB_CyPy_Entity_CyPy_Entity
//#define STUB_CyPy_Entity_CyPy_Entity
   CyPy_Entity::CyPy_Entity(Py::PythonClassInstanceWeak* self, Ref<Entity> value)
    : CyPy_LocatedEntityBase(self, value)
  {
    
  }
#endif //STUB_CyPy_Entity_CyPy_Entity

#ifndef STUB_CyPy_Entity_CyPy_Entity_DTOR
//#define STUB_CyPy_Entity_CyPy_Entity_DTOR
   CyPy_Entity::~CyPy_Entity()
  {
    
  }
#endif //STUB_CyPy_Entity_CyPy_Entity_DTOR

#ifndef STUB_CyPy_Entity_init_type
//#define STUB_CyPy_Entity_init_type
   void CyPy_Entity::init_type()
  {
    
  }
#endif //STUB_CyPy_Entity_init_type

#ifndef STUB_CyPy_Entity_send_world
//#define STUB_CyPy_Entity_send_world
   Py::Object CyPy_Entity::send_world(const Ref<Entity>& entity, const Py::Tuple& args)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_send_world

#ifndef STUB_CyPy_Entity_start_task
//#define STUB_CyPy_Entity_start_task
   Py::Object CyPy_Entity::start_task(const Ref<Entity>& entity, const Py::Tuple& args)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_start_task

#ifndef STUB_CyPy_Entity_update_task
//#define STUB_CyPy_Entity_update_task
   Py::Object CyPy_Entity::update_task(const Ref<Entity>& entity)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_update_task

#ifndef STUB_CyPy_Entity_start_action
//#define STUB_CyPy_Entity_start_action
   Py::Object CyPy_Entity::start_action(const Ref<Entity>& entity, const Py::Tuple& args)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_start_action

#ifndef STUB_CyPy_Entity_mod_property
//#define STUB_CyPy_Entity_mod_property
   Py::Object CyPy_Entity::mod_property(const Ref<Entity>& entity, const Py::Tuple& args)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_mod_property

#ifndef STUB_CyPy_Entity_getattro
//#define STUB_CyPy_Entity_getattro
  Py::Object CyPy_Entity::getattro(const Py::String&)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_getattro

#ifndef STUB_CyPy_Entity_setattro
//#define STUB_CyPy_Entity_setattro
  int CyPy_Entity::setattro(const Py::String& name, const Py::Object& attr)
  {
    return 0;
  }
#endif //STUB_CyPy_Entity_setattro

#ifndef STUB_CyPy_Entity_send_world
//#define STUB_CyPy_Entity_send_world
  Py::Object CyPy_Entity::send_world(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_send_world

#ifndef STUB_CyPy_Entity_start_task
//#define STUB_CyPy_Entity_start_task
  Py::Object CyPy_Entity::start_task(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_start_task

#ifndef STUB_CyPy_Entity_start_action
//#define STUB_CyPy_Entity_start_action
  Py::Object CyPy_Entity::start_action(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_start_action

#ifndef STUB_CyPy_Entity_update_task
//#define STUB_CyPy_Entity_update_task
  Py::Object CyPy_Entity::update_task()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_update_task

#ifndef STUB_CyPy_Entity_mod_property
//#define STUB_CyPy_Entity_mod_property
  Py::Object CyPy_Entity::mod_property(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_mod_property

#ifndef STUB_CyPy_Entity_find_in_contains
//#define STUB_CyPy_Entity_find_in_contains
  Py::Object CyPy_Entity::find_in_contains(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_find_in_contains

#ifndef STUB_CyPy_Entity_get_parent_domain
//#define STUB_CyPy_Entity_get_parent_domain
  Py::Object CyPy_Entity::get_parent_domain()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_get_parent_domain

#ifndef STUB_CyPy_Entity_create_new_entity
//#define STUB_CyPy_Entity_create_new_entity
  Py::Object CyPy_Entity::create_new_entity(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Entity_create_new_entity


#endif