// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_EntityProps_custom.h file.

#ifndef STUB_RULES_SIMULATION_PYTHON_CYPY_ENTITYPROPS_H
#define STUB_RULES_SIMULATION_PYTHON_CYPY_ENTITYPROPS_H

#include "rules/simulation/python/CyPy_EntityProps.h"
#include "stubCyPy_EntityProps_custom.h"

#ifndef STUB_CyPy_EntityProps_CyPy_EntityProps
//#define STUB_CyPy_EntityProps_CyPy_EntityProps
   CyPy_EntityProps::CyPy_EntityProps(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : WrapperBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_EntityProps_CyPy_EntityProps

#ifndef STUB_CyPy_EntityProps_CyPy_EntityProps
//#define STUB_CyPy_EntityProps_CyPy_EntityProps
   CyPy_EntityProps::CyPy_EntityProps(Py::PythonClassInstance* self, Ref<Entity> value)
    : WrapperBase(self, value)
  {
    
  }
#endif //STUB_CyPy_EntityProps_CyPy_EntityProps

#ifndef STUB_CyPy_EntityProps_init_type
//#define STUB_CyPy_EntityProps_init_type
   void CyPy_EntityProps::init_type()
  {
    
  }
#endif //STUB_CyPy_EntityProps_init_type

#ifndef STUB_CyPy_EntityProps_getattro
//#define STUB_CyPy_EntityProps_getattro
  Py::Object CyPy_EntityProps::getattro(const Py::String& name)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_EntityProps_getattro

#ifndef STUB_CyPy_EntityProps_setattro
//#define STUB_CyPy_EntityProps_setattro
  int CyPy_EntityProps::setattro(const Py::String& name, const Py::Object& attr)
  {
    return 0;
  }
#endif //STUB_CyPy_EntityProps_setattro

#ifndef STUB_CyPy_EntityProps_mapping_subscript
//#define STUB_CyPy_EntityProps_mapping_subscript
  Py::Object CyPy_EntityProps::mapping_subscript(const Py::Object&)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_EntityProps_mapping_subscript


#endif