// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_World_custom.h file.

#ifndef STUB_RULES_SIMULATION_PYTHON_CYPY_WORLD_H
#define STUB_RULES_SIMULATION_PYTHON_CYPY_WORLD_H

#include "rules/simulation/python/CyPy_World.h"
#include "stubCyPy_World_custom.h"

#ifndef STUB_CyPy_World_CyPy_World
//#define STUB_CyPy_World_CyPy_World
   CyPy_World::CyPy_World(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : WrapperBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_World_CyPy_World

#ifndef STUB_CyPy_World_CyPy_World
//#define STUB_CyPy_World_CyPy_World
   CyPy_World::CyPy_World(Py::PythonClassInstance* self, BaseWorld* value)
    : WrapperBase(self, value)
  {
    
  }
#endif //STUB_CyPy_World_CyPy_World

#ifndef STUB_CyPy_World_init_type
//#define STUB_CyPy_World_init_type
   void CyPy_World::init_type()
  {
    
  }
#endif //STUB_CyPy_World_init_type

#ifndef STUB_CyPy_World_get_time
//#define STUB_CyPy_World_get_time
  Py::Object CyPy_World::get_time()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_World_get_time

#ifndef STUB_CyPy_World_get_entity
//#define STUB_CyPy_World_get_entity
  Py::Object CyPy_World::get_entity(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_World_get_entity

#ifndef STUB_CyPy_World_match_entity
//#define STUB_CyPy_World_match_entity
  Py::Object CyPy_World::match_entity(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_World_match_entity


#endif