// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubDateTime_custom.h file.

#include "modules/DateTime.h"
#include "stubDateTime_custom.h"

#ifndef STUB_MODULES_DATETIME_H
#define STUB_MODULES_DATETIME_H

#ifndef STUB_DateTime_set
//#define STUB_DateTime_set
  void DateTime::set(unsigned int)
  {
    
  }
#endif //STUB_DateTime_set

#ifndef STUB_DateTime_DateTime
//#define STUB_DateTime_DateTime
   DateTime::DateTime(char *)
  {
    
  }
#endif //STUB_DateTime_DateTime

#ifndef STUB_DateTime_DateTime
//#define STUB_DateTime_DateTime
   DateTime::DateTime(int)
  {
    
  }
#endif //STUB_DateTime_DateTime

#ifndef STUB_DateTime_DateTime
//#define STUB_DateTime_DateTime
   DateTime::DateTime(int, int, int, int, int, int)
  {
    
  }
#endif //STUB_DateTime_DateTime

#ifndef STUB_DateTime_isValid
//#define STUB_DateTime_isValid
  bool DateTime::isValid() const
  {
    return false;
  }
#endif //STUB_DateTime_isValid

#ifndef STUB_DateTime_seconds
//#define STUB_DateTime_seconds
  int DateTime::seconds()
  {
    return 0;
  }
#endif //STUB_DateTime_seconds

#ifndef STUB_DateTime_update
//#define STUB_DateTime_update
  void DateTime::update(int)
  {
    
  }
#endif //STUB_DateTime_update

#ifndef STUB_DateTime_asString
//#define STUB_DateTime_asString
  std::string DateTime::asString()
  {
    return "";
  }
#endif //STUB_DateTime_asString

#ifndef STUB_DateTime_operator_EQUALS
//#define STUB_DateTime_operator_EQUALS
  bool DateTime::operator==(const DateTime &) const
  {
    return false;
  }
#endif //STUB_DateTime_operator_EQUALS


#endif