// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubReferenceCounted_custom.h file.

#ifndef STUB_MODULES_REFERENCECOUNTED_H
#define STUB_MODULES_REFERENCECOUNTED_H

#include "modules/ReferenceCounted.h"
#include "stubReferenceCounted_custom.h"


#endif