// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubTerrainContext_custom.h file.

#ifndef STUB_MODULES_TERRAINCONTEXT_H
#define STUB_MODULES_TERRAINCONTEXT_H

#include "modules/TerrainContext.h"
#include "stubTerrainContext_custom.h"


#endif