#!/usr/bin/env python

import sys

build_id = open(sys.argv[2], 'w')

build_id.write(
"""// This file was generated by gen_buildid.py
// Do not edit

#include "common/const.h"

namespace consts {

  const char * buildId = "%s";
}
""" % sys.argv[1])

build_id.close()
