// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubAwarenessStore_custom.h file.

#include "rulesets/mind/AwarenessStore.h"
#include "stubAwarenessStore_custom.h"

#ifndef STUB_RULESETS_MIND_AWARENESSSTORE_H
#define STUB_RULESETS_MIND_AWARENESSSTORE_H

#ifndef STUB_AwarenessStore_AwarenessStore
//#define STUB_AwarenessStore_AwarenessStore
   AwarenessStore::AwarenessStore(float agentRadius, float agentHeight, IHeightProvider& heightProvider, int tileSize )
  {
    
  }
#endif //STUB_AwarenessStore_AwarenessStore

#ifndef STUB_AwarenessStore_AwarenessStore_DTOR
//#define STUB_AwarenessStore_AwarenessStore_DTOR
   AwarenessStore::~AwarenessStore()
  {
    
  }
#endif //STUB_AwarenessStore_AwarenessStore_DTOR

#ifndef STUB_AwarenessStore_requestAwareness
//#define STUB_AwarenessStore_requestAwareness
  std::shared_ptr<Awareness> AwarenessStore::requestAwareness(const LocatedEntity& domainEntity)
  {
    return *static_cast<std::shared_ptr<Awareness>*>(nullptr);
  }
#endif //STUB_AwarenessStore_requestAwareness


#endif