// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_Element_custom.h file.

#ifndef STUB_RULES_PYTHON_CYPY_ELEMENT_H
#define STUB_RULES_PYTHON_CYPY_ELEMENT_H

#include "rules/python/CyPy_Element.h"
#include "stubCyPy_Element_custom.h"

#ifndef STUB_CyPy_ElementList_CyPy_ElementList
//#define STUB_CyPy_ElementList_CyPy_ElementList
   CyPy_ElementList::CyPy_ElementList(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : WrapperBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_ElementList_CyPy_ElementList

#ifndef STUB_CyPy_ElementList_CyPy_ElementList
//#define STUB_CyPy_ElementList_CyPy_ElementList
   CyPy_ElementList::CyPy_ElementList(Py::PythonClassInstance* self, Atlas::Message::ListType element)
    : WrapperBase(self, element)
  {
    
  }
#endif //STUB_CyPy_ElementList_CyPy_ElementList

#ifndef STUB_CyPy_ElementList_init_type
//#define STUB_CyPy_ElementList_init_type
   void CyPy_ElementList::init_type()
  {
    
  }
#endif //STUB_CyPy_ElementList_init_type

#ifndef STUB_CyPy_ElementList_repr
//#define STUB_CyPy_ElementList_repr
  Py::Object CyPy_ElementList::repr()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementList_repr

#ifndef STUB_CyPy_ElementList_rich_compare
//#define STUB_CyPy_ElementList_rich_compare
  Py::Object CyPy_ElementList::rich_compare(const Py::Object& other, int op)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementList_rich_compare

#ifndef STUB_CyPy_ElementList_sequence_length
//#define STUB_CyPy_ElementList_sequence_length
  PyCxx_ssize_t CyPy_ElementList::sequence_length()
  {
    return *static_cast<PyCxx_ssize_t*>(nullptr);
  }
#endif //STUB_CyPy_ElementList_sequence_length

#ifndef STUB_CyPy_ElementList_sequence_concat
//#define STUB_CyPy_ElementList_sequence_concat
  Py::Object CyPy_ElementList::sequence_concat(const Py::Object&)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementList_sequence_concat

#ifndef STUB_CyPy_ElementList_sequence_repeat
//#define STUB_CyPy_ElementList_sequence_repeat
  Py::Object CyPy_ElementList::sequence_repeat(Py_ssize_t)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementList_sequence_repeat

#ifndef STUB_CyPy_ElementList_sequence_item
//#define STUB_CyPy_ElementList_sequence_item
  Py::Object CyPy_ElementList::sequence_item(Py_ssize_t)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementList_sequence_item

#ifndef STUB_CyPy_ElementList_sequence_ass_item
//#define STUB_CyPy_ElementList_sequence_ass_item
  int CyPy_ElementList::sequence_ass_item(Py_ssize_t, const Py::Object&)
  {
    return 0;
  }
#endif //STUB_CyPy_ElementList_sequence_ass_item

#ifndef STUB_CyPy_ElementList_sequence_inplace_concat
//#define STUB_CyPy_ElementList_sequence_inplace_concat
  Py::Object CyPy_ElementList::sequence_inplace_concat(const Py::Object&)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementList_sequence_inplace_concat

#ifndef STUB_CyPy_ElementList_sequence_inplace_repeat
//#define STUB_CyPy_ElementList_sequence_inplace_repeat
  Py::Object CyPy_ElementList::sequence_inplace_repeat(Py_ssize_t)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementList_sequence_inplace_repeat

#ifndef STUB_CyPy_ElementList_sequence_contains
//#define STUB_CyPy_ElementList_sequence_contains
  int CyPy_ElementList::sequence_contains(const Py::Object&)
  {
    return 0;
  }
#endif //STUB_CyPy_ElementList_sequence_contains

#ifndef STUB_CyPy_ElementList_iter
//#define STUB_CyPy_ElementList_iter
  Py::Object CyPy_ElementList::iter()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementList_iter


#ifndef STUB_CyPy_ElementMap_CyPy_ElementMap
//#define STUB_CyPy_ElementMap_CyPy_ElementMap
   CyPy_ElementMap::CyPy_ElementMap(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : WrapperBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_ElementMap_CyPy_ElementMap

#ifndef STUB_CyPy_ElementMap_CyPy_ElementMap
//#define STUB_CyPy_ElementMap_CyPy_ElementMap
   CyPy_ElementMap::CyPy_ElementMap(Py::PythonClassInstance* self, Atlas::Message::MapType element)
    : WrapperBase(self, element)
  {
    
  }
#endif //STUB_CyPy_ElementMap_CyPy_ElementMap

#ifndef STUB_CyPy_ElementMap_init_type
//#define STUB_CyPy_ElementMap_init_type
   void CyPy_ElementMap::init_type()
  {
    
  }
#endif //STUB_CyPy_ElementMap_init_type

#ifndef STUB_CyPy_ElementMap_repr
//#define STUB_CyPy_ElementMap_repr
  Py::Object CyPy_ElementMap::repr()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementMap_repr

#ifndef STUB_CyPy_ElementMap_rich_compare
//#define STUB_CyPy_ElementMap_rich_compare
  Py::Object CyPy_ElementMap::rich_compare(const Py::Object& other, int op)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementMap_rich_compare

#ifndef STUB_CyPy_ElementMap_mapping_subscript
//#define STUB_CyPy_ElementMap_mapping_subscript
  Py::Object CyPy_ElementMap::mapping_subscript(const Py::Object&)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementMap_mapping_subscript

#ifndef STUB_CyPy_ElementMap_sequence_contains
//#define STUB_CyPy_ElementMap_sequence_contains
  int CyPy_ElementMap::sequence_contains(const Py::Object&)
  {
    return 0;
  }
#endif //STUB_CyPy_ElementMap_sequence_contains

#ifndef STUB_CyPy_ElementMap_mapping_ass_subscript
//#define STUB_CyPy_ElementMap_mapping_ass_subscript
  int CyPy_ElementMap::mapping_ass_subscript(const Py::Object&, const Py::Object&)
  {
    return 0;
  }
#endif //STUB_CyPy_ElementMap_mapping_ass_subscript

#ifndef STUB_CyPy_ElementMap_getattro
//#define STUB_CyPy_ElementMap_getattro
  Py::Object CyPy_ElementMap::getattro(const Py::String&)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementMap_getattro

#ifndef STUB_CyPy_ElementMap_setattro
//#define STUB_CyPy_ElementMap_setattro
  int CyPy_ElementMap::setattro(const Py::String& name, const Py::Object& attr)
  {
    return 0;
  }
#endif //STUB_CyPy_ElementMap_setattro

#ifndef STUB_CyPy_ElementMap_items
//#define STUB_CyPy_ElementMap_items
  Py::Object CyPy_ElementMap::items()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_ElementMap_items


#ifndef STUB_CyPy_Element_wrap
//#define STUB_CyPy_Element_wrap
   Py::Object CyPy_Element::wrap(Atlas::Message::Element value)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_wrap

#ifndef STUB_CyPy_Element_asPyObject
//#define STUB_CyPy_Element_asPyObject
   Py::Object CyPy_Element::asPyObject(const Atlas::Message::Element& obj, bool useNativePythonType)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_asPyObject

#ifndef STUB_CyPy_Element_asElement
//#define STUB_CyPy_Element_asElement
   Atlas::Message::Element CyPy_Element::asElement(const Py::Object& o)
  {
    return *static_cast< Atlas::Message::Element*>(nullptr);
  }
#endif //STUB_CyPy_Element_asElement

#ifndef STUB_CyPy_Element_listAsElement
//#define STUB_CyPy_Element_listAsElement
   Atlas::Message::ListType CyPy_Element::listAsElement(const Py::List& list)
  {
    return *static_cast< Atlas::Message::ListType*>(nullptr);
  }
#endif //STUB_CyPy_Element_listAsElement

#ifndef STUB_CyPy_Element_sequenceAsElement
//#define STUB_CyPy_Element_sequenceAsElement
   Atlas::Message::ListType CyPy_Element::sequenceAsElement(const Py::Sequence& list)
  {
    return *static_cast< Atlas::Message::ListType*>(nullptr);
  }
#endif //STUB_CyPy_Element_sequenceAsElement

#ifndef STUB_CyPy_Element_dictAsElement
//#define STUB_CyPy_Element_dictAsElement
   Atlas::Message::MapType CyPy_Element::dictAsElement(const Py::Dict& dict)
  {
    return *static_cast< Atlas::Message::MapType*>(nullptr);
  }
#endif //STUB_CyPy_Element_dictAsElement

#ifndef STUB_CyPy_Element_mapAsPyObject
//#define STUB_CyPy_Element_mapAsPyObject
   Py::Object CyPy_Element::mapAsPyObject(const Atlas::Message::MapType& map, bool useNativePythonType)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_mapAsPyObject

#ifndef STUB_CyPy_Element_listAsPyObject
//#define STUB_CyPy_Element_listAsPyObject
   Py::Object CyPy_Element::listAsPyObject(const Atlas::Message::ListType& list, bool useNativePythonType)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Element_listAsPyObject


#endif