// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_EntityLocation_custom.h file.

#ifndef STUB_RULES_PYTHON_CYPY_ENTITYLOCATION_H
#define STUB_RULES_PYTHON_CYPY_ENTITYLOCATION_H

#include "rules/python/CyPy_EntityLocation.h"
#include "stubCyPy_EntityLocation_custom.h"

#ifndef STUB_CyPy_EntityLocation_CyPy_EntityLocation
//#define STUB_CyPy_EntityLocation_CyPy_EntityLocation
   CyPy_EntityLocation::CyPy_EntityLocation(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : WrapperBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_EntityLocation_CyPy_EntityLocation

#ifndef STUB_CyPy_EntityLocation_CyPy_EntityLocation
//#define STUB_CyPy_EntityLocation_CyPy_EntityLocation
   CyPy_EntityLocation::CyPy_EntityLocation(Py::PythonClassInstance* self, EntityLocation value)
    : WrapperBase(self, value)
  {
    
  }
#endif //STUB_CyPy_EntityLocation_CyPy_EntityLocation

#ifndef STUB_CyPy_EntityLocation_init_type
//#define STUB_CyPy_EntityLocation_init_type
   void CyPy_EntityLocation::init_type()
  {
    
  }
#endif //STUB_CyPy_EntityLocation_init_type

#ifndef STUB_CyPy_EntityLocation_getattro
//#define STUB_CyPy_EntityLocation_getattro
  Py::Object CyPy_EntityLocation::getattro(const Py::String&)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_EntityLocation_getattro

#ifndef STUB_CyPy_EntityLocation_setattro
//#define STUB_CyPy_EntityLocation_setattro
  int CyPy_EntityLocation::setattro(const Py::String& name, const Py::Object& attr)
  {
    return 0;
  }
#endif //STUB_CyPy_EntityLocation_setattro

#ifndef STUB_CyPy_EntityLocation_copy
//#define STUB_CyPy_EntityLocation_copy
  Py::Object CyPy_EntityLocation::copy()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_EntityLocation_copy


#endif