// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_Ball_custom.h file.

#ifndef STUB_RULES_PYTHON_CYPY_BALL_H
#define STUB_RULES_PYTHON_CYPY_BALL_H

#include "rules/python/CyPy_Ball.h"
#include "stubCyPy_Ball_custom.h"

#ifndef STUB_CyPy_Ball_CyPy_Ball
//#define STUB_CyPy_Ball_CyPy_Ball
   CyPy_Ball::CyPy_Ball(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : WrapperBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_Ball_CyPy_Ball

#ifndef STUB_CyPy_Ball_CyPy_Ball
//#define STUB_CyPy_Ball_CyPy_Ball
   CyPy_Ball::CyPy_Ball(Py::PythonClassInstance* self, WFMath::Ball<3> value)
    : WrapperBase(self, value)
  {
    
  }
#endif //STUB_CyPy_Ball_CyPy_Ball

#ifndef STUB_CyPy_Ball_parse
//#define STUB_CyPy_Ball_parse
   WFMath::Ball<3> CyPy_Ball::parse(const Py::Object& object)
  {
    return *static_cast< WFMath::Ball<3>*>(nullptr);
  }
#endif //STUB_CyPy_Ball_parse

#ifndef STUB_CyPy_Ball_init_type
//#define STUB_CyPy_Ball_init_type
   void CyPy_Ball::init_type()
  {
    
  }
#endif //STUB_CyPy_Ball_init_type

#ifndef STUB_CyPy_Ball_repr
//#define STUB_CyPy_Ball_repr
  Py::Object CyPy_Ball::repr()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Ball_repr

#ifndef STUB_CyPy_Ball_rich_compare
//#define STUB_CyPy_Ball_rich_compare
  Py::Object CyPy_Ball::rich_compare(const Py::Object& other, int type)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Ball_rich_compare


#endif