// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubWrapperBase_custom.h file.

#ifndef STUB_RULES_PYTHON_WRAPPERBASE_H
#define STUB_RULES_PYTHON_WRAPPERBASE_H

#include "rules/python/WrapperBase.h"
#include "stubWrapperBase_custom.h"

#ifndef STUB_WrapperBase_WrapperBase
//#define STUB_WrapperBase_WrapperBase
  template <typename TValue,typename TClassInstance,typename TPythonClass>
   WrapperBase<TValue,TClassInstance,TPythonClass>::WrapperBase(TClassInstance* self, const Py::Tuple& args, const Py::Dict& kwds)
    : Py::PythonClass(self, args, kwds)
  {
    
  }
#endif //STUB_WrapperBase_WrapperBase

#ifndef STUB_WrapperBase_wrap
//#define STUB_WrapperBase_wrap
  template <typename TValue,typename TClassInstance,typename TPythonClass>
   Py::Object WrapperBase<TValue,TClassInstance,TPythonClass>::wrap(TValue value)
  {
    return *static_cast< Py::Object*>(nullptr);
  }
#endif //STUB_WrapperBase_wrap

#ifndef STUB_WrapperBase_value
//#define STUB_WrapperBase_value
  template <typename TValue,typename TClassInstance,typename TPythonClass>
   TValue& WrapperBase<TValue,TClassInstance,TPythonClass>::value(const Py::Object& object)
  {
    return *static_cast< TValue*>(nullptr);
  }
#endif //STUB_WrapperBase_value

#ifndef STUB_WrapperBase_WrapperBase
//#define STUB_WrapperBase_WrapperBase
  template <typename TValue,typename TClassInstance,typename TPythonClass>
   WrapperBase<TValue,TClassInstance,TPythonClass>::WrapperBase(TClassInstance* self, TValue value)
    : Py::PythonClass(self, value)
  {
    
  }
#endif //STUB_WrapperBase_WrapperBase


#endif