// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_Atlas_custom.h file.

#ifndef STUB_RULES_PYTHON_CYPY_ATLAS_H
#define STUB_RULES_PYTHON_CYPY_ATLAS_H

#include "rules/python/CyPy_Atlas.h"
#include "stubCyPy_Atlas_custom.h"

#ifndef STUB_CyPy_Atlas_CyPy_Atlas
//#define STUB_CyPy_Atlas_CyPy_Atlas
   CyPy_Atlas::CyPy_Atlas()
    : Py::ExtensionModule()
  {
    
  }
#endif //STUB_CyPy_Atlas_CyPy_Atlas

#ifndef STUB_CyPy_Atlas_init
//#define STUB_CyPy_Atlas_init
   std::string CyPy_Atlas::init()
  {
    return "";
  }
#endif //STUB_CyPy_Atlas_init


#endif