// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_Props_custom.h file.

#ifndef STUB_RULES_PYTHON_CYPY_PROPS_H
#define STUB_RULES_PYTHON_CYPY_PROPS_H

#include "rules/python/CyPy_Props.h"
#include "stubCyPy_Props_custom.h"

#ifndef STUB_CyPy_Props_CyPy_Props
//#define STUB_CyPy_Props_CyPy_Props
   CyPy_Props::CyPy_Props(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : WrapperBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_Props_CyPy_Props

#ifndef STUB_CyPy_Props_CyPy_Props
//#define STUB_CyPy_Props_CyPy_Props
   CyPy_Props::CyPy_Props(Py::PythonClassInstance* self, Ref<LocatedEntity> value)
    : WrapperBase(self, value)
  {
    
  }
#endif //STUB_CyPy_Props_CyPy_Props

#ifndef STUB_CyPy_Props_init_type
//#define STUB_CyPy_Props_init_type
   void CyPy_Props::init_type()
  {
    
  }
#endif //STUB_CyPy_Props_init_type

#ifndef STUB_CyPy_Props_getattro
//#define STUB_CyPy_Props_getattro
  Py::Object CyPy_Props::getattro(const Py::String& name)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Props_getattro

#ifndef STUB_CyPy_Props_setattro
//#define STUB_CyPy_Props_setattro
  int CyPy_Props::setattro(const Py::String& name, const Py::Object& attr)
  {
    return 0;
  }
#endif //STUB_CyPy_Props_setattro

#ifndef STUB_CyPy_Props_mapping_subscript
//#define STUB_CyPy_Props_mapping_subscript
  Py::Object CyPy_Props::mapping_subscript(const Py::Object&)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_Props_mapping_subscript


#endif