// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPythonScriptFactory_impl_custom.h file.

#ifndef STUB_RULES_PYTHON_PYTHONSCRIPTFACTORY_IMPL_H
#define STUB_RULES_PYTHON_PYTHONSCRIPTFACTORY_IMPL_H

#include "rules/python/PythonScriptFactory_impl.h"
#include "stubPythonScriptFactory_impl_custom.h"

#endif