// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubconst_custom.h file.

#include "common/const.h"
#include "stubconst_custom.h"

#ifndef STUB_COMMON_CONST_H
#define STUB_COMMON_CONST_H

#endif