// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPropertyFactory_custom.h file.

#include "common/PropertyFactory.h"
#include "stubPropertyFactory_custom.h"

#ifndef STUB_COMMON_PROPERTYFACTORY_H
#define STUB_COMMON_PROPERTYFACTORY_H

#ifndef STUB_PropertyKit_PropertyKit_DTOR
//#define STUB_PropertyKit_PropertyKit_DTOR
   PropertyKit::~PropertyKit()
  {
    
  }
#endif //STUB_PropertyKit_PropertyKit_DTOR

#ifndef STUB_PropertyKit_newProperty
//#define STUB_PropertyKit_newProperty
  PropertyBase* PropertyKit::newProperty()
  {
    return nullptr;
  }
#endif //STUB_PropertyKit_newProperty

#ifndef STUB_PropertyKit_duplicateFactory
//#define STUB_PropertyKit_duplicateFactory
  PropertyKit* PropertyKit::duplicateFactory() const
  {
    return nullptr;
  }
#endif //STUB_PropertyKit_duplicateFactory


#ifndef STUB_PropertyFactory_newProperty
//#define STUB_PropertyFactory_newProperty
  template <typename T>
  PropertyBase* PropertyFactory<T>::newProperty()
  {
    return nullptr;
  }
#endif //STUB_PropertyFactory_newProperty

#ifndef STUB_PropertyFactory_duplicateFactory
//#define STUB_PropertyFactory_duplicateFactory
  template <typename T>
  PropertyFactory<T>* PropertyFactory<T>::duplicateFactory() const
  {
    return nullptr;
  }
#endif //STUB_PropertyFactory_duplicateFactory


#endif