// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubid_custom.h file.

#include "common/id.h"
#include "stubid_custom.h"

#ifndef STUB_COMMON_ID_H
#define STUB_COMMON_ID_H

#endif