// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCommSocket_custom.h file.

#ifndef STUB_COMMON_COMMSOCKET_H
#define STUB_COMMON_COMMSOCKET_H

#include "common/CommSocket.h"
#include "stubCommSocket_custom.h"

#ifndef STUB_CommSocket_disconnect
//#define STUB_CommSocket_disconnect
  void CommSocket::disconnect()
  {
    
  }
#endif //STUB_CommSocket_disconnect

#ifndef STUB_CommSocket_flush
//#define STUB_CommSocket_flush
  int CommSocket::flush()
  {
    return 0;
  }
#endif //STUB_CommSocket_flush


#endif