// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubMainLoop_custom.h file.

#ifndef STUB_COMMON_MAINLOOP_H
#define STUB_COMMON_MAINLOOP_H

#include "common/MainLoop.h"
#include "stubMainLoop_custom.h"

#ifndef STUB_MainLoop_run
//#define STUB_MainLoop_run
   void MainLoop::run(bool daemon, boost::asio::io_service& io_service, OperationsHandler& operationsHandler, const Callbacks& callbacks)
  {
    
  }
#endif //STUB_MainLoop_run


#endif