// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubScriptKit_custom.h file.

#ifndef STUB_COMMON_SCRIPTKIT_H
#define STUB_COMMON_SCRIPTKIT_H

#include "common/ScriptKit.h"
#include "stubScriptKit_custom.h"

#ifndef STUB_ScriptKit_package
//#define STUB_ScriptKit_package
  template <typename T>
  const std::string& ScriptKit<T>::package() const
  {
    static std::string _static_instance; return _static_instance;
  }
#endif //STUB_ScriptKit_package

#ifndef STUB_ScriptKit_addScript
//#define STUB_ScriptKit_addScript
  template <typename T>
  int ScriptKit<T>::addScript(T& entity) const
  {
    return 0;
  }
#endif //STUB_ScriptKit_addScript

#ifndef STUB_ScriptKit_refreshClass
//#define STUB_ScriptKit_refreshClass
  template <typename T>
  int ScriptKit<T>::refreshClass()
  {
    return 0;
  }
#endif //STUB_ScriptKit_refreshClass


#endif