// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubRepeatedTask_custom.h file.

#ifndef STUB_COMMON_REPEATEDTASK_H
#define STUB_COMMON_REPEATEDTASK_H

#include "common/RepeatedTask.h"
#include "stubRepeatedTask_custom.h"

#ifndef STUB_RepeatedTask_RepeatedTask
//#define STUB_RepeatedTask_RepeatedTask
   RepeatedTask::RepeatedTask(boost::asio::io_context& io_context, std::chrono::steady_clock::duration interval, std::function<void()> function)
  {
    
  }
#endif //STUB_RepeatedTask_RepeatedTask

#ifndef STUB_RepeatedTask_cancel
//#define STUB_RepeatedTask_cancel
  void RepeatedTask::cancel()
  {
    
  }
#endif //STUB_RepeatedTask_cancel

#ifndef STUB_RepeatedTask_executeTask
//#define STUB_RepeatedTask_executeTask
  void RepeatedTask::executeTask()
  {
    
  }
#endif //STUB_RepeatedTask_executeTask


#endif