// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubSingleton_custom.h file.

#ifndef STUB_COMMON_SINGLETON_H
#define STUB_COMMON_SINGLETON_H

#include "common/Singleton.h"
#include "stubSingleton_custom.h"


#endif