// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubrandom_custom.h file.

#include "common/random.h"
#include "stubrandom_custom.h"

#ifndef STUB_COMMON_RANDOM_H
#define STUB_COMMON_RANDOM_H

#endif