// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPropertyFactory_impl_custom.h file.

#include "common/PropertyFactory_impl.h"
#include "stubPropertyFactory_impl_custom.h"

#ifndef STUB_COMMON_PROPERTYFACTORY_IMPL_H
#define STUB_COMMON_PROPERTYFACTORY_IMPL_H

#endif