// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPickup_custom.h file.

#include "common/Pickup.h"
#include "stubPickup_custom.h"

#ifndef STUB_COMMON_PICKUP_H
#define STUB_COMMON_PICKUP_H

namespace Atlas {
namespace Objects {
namespace Operation {


}  // namespace Operation
}  // namespace Objects
}  // namespace Atlas

#endif