// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubAtlasQuery_custom.h file.

#ifndef STUB_COMMON_ATLASQUERY_H
#define STUB_COMMON_ATLASQUERY_H

#include "common/AtlasQuery.h"
#include "stubAtlasQuery_custom.h"

#ifndef STUB_AtlasQuery_find
//#define STUB_AtlasQuery_find
   void AtlasQuery::find(const Atlas::Message::Element& element, const std::string& name, const std::function<void(const T&)>& callback)
  {
    
  }
#endif //STUB_AtlasQuery_find

#ifndef STUB_AtlasQuery_find
//#define STUB_AtlasQuery_find
   void AtlasQuery::find(const Atlas::Message::MapType& map, const std::string& name, const std::function<void(const T&)>& callback)
  {
    
  }
#endif //STUB_AtlasQuery_find


#endif