// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubBurn_custom.h file.

#include "common/Burn.h"
#include "stubBurn_custom.h"

#ifndef STUB_COMMON_BURN_H
#define STUB_COMMON_BURN_H

namespace Atlas {
namespace Objects {
namespace Operation {


}  // namespace Operation
}  // namespace Objects
}  // namespace Atlas

#endif