// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubnls_custom.h file.

#include "common/nls.h"
#include "stubnls_custom.h"

#ifndef STUB_COMMON_NLS_H
#define STUB_COMMON_NLS_H

#endif