// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubSetup_custom.h file.

#include "common/Setup.h"
#include "stubSetup_custom.h"

#ifndef STUB_COMMON_SETUP_H
#define STUB_COMMON_SETUP_H

namespace Atlas {
namespace Objects {
namespace Operation {


}  // namespace Operation
}  // namespace Objects
}  // namespace Atlas

#endif