// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubTaskKit_custom.h file.

#include "common/TaskKit.h"
#include "stubTaskKit_custom.h"

#ifndef STUB_COMMON_TASKKIT_H
#define STUB_COMMON_TASKKIT_H

#ifndef STUB_TaskKit_TaskKit
//#define STUB_TaskKit_TaskKit
   TaskKit::TaskKit()
    : m_target(nullptr),m_scriptFactory(nullptr)
  {
    
  }
#endif //STUB_TaskKit_TaskKit

#ifndef STUB_TaskKit_TaskKit_DTOR
//#define STUB_TaskKit_TaskKit_DTOR
   TaskKit::~TaskKit()
  {
    
  }
#endif //STUB_TaskKit_TaskKit_DTOR

#ifndef STUB_TaskKit_checkTarget
//#define STUB_TaskKit_checkTarget
  int TaskKit::checkTarget(LocatedEntity * target)
  {
    return 0;
  }
#endif //STUB_TaskKit_checkTarget

#ifndef STUB_TaskKit_newTask
//#define STUB_TaskKit_newTask
  Task* TaskKit::newTask(LocatedEntity & chr)
  {
    return nullptr;
  }
#endif //STUB_TaskKit_newTask


#endif