// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubLink_custom.h file.

#ifndef STUB_COMMON_LINK_H
#define STUB_COMMON_LINK_H

#include "common/Link.h"
#include "stubLink_custom.h"

#ifndef STUB_Link_Link
//#define STUB_Link_Link
   Link::Link(CommSocket & commSocket, RouterId id)
    : Router(commSocket, id)
    , m_encoder(nullptr)
  {
    
  }
#endif //STUB_Link_Link

#ifndef STUB_Link_Link_DTOR
//#define STUB_Link_Link_DTOR
   Link::~Link()
  {
    
  }
#endif //STUB_Link_Link_DTOR

#ifndef STUB_Link_send
//#define STUB_Link_send
  void Link::send(const Operation & op) const
  {
    
  }
#endif //STUB_Link_send

#ifndef STUB_Link_send
//#define STUB_Link_send
  void Link::send(const OpVector& opVector) const
  {
    
  }
#endif //STUB_Link_send

#ifndef STUB_Link_sendError
//#define STUB_Link_sendError
  void Link::sendError(const Operation & op, const std::string &, const std::string &) const
  {
    
  }
#endif //STUB_Link_sendError

#ifndef STUB_Link_disconnect
//#define STUB_Link_disconnect
  void Link::disconnect()
  {
    
  }
#endif //STUB_Link_disconnect

#ifndef STUB_Link_notifyConnectionComplete
//#define STUB_Link_notifyConnectionComplete
  void Link::notifyConnectionComplete()
  {
    
  }
#endif //STUB_Link_notifyConnectionComplete


#endif