// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubEat_custom.h file.

#ifndef STUB_COMMON_EAT_H
#define STUB_COMMON_EAT_H

#include "common/Eat.h"
#include "stubEat_custom.h"

namespace Atlas {
namespace Objects {
namespace Operation {


}  // namespace Operation
}  // namespace Objects
}  // namespace Atlas

#endif