// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPossess_custom.h file.

#include "common/Possess.h"
#include "stubPossess_custom.h"

#ifndef STUB_COMMON_POSSESS_H
#define STUB_COMMON_POSSESS_H

namespace Atlas {
namespace Objects {
namespace Operation {


}  // namespace Operation
}  // namespace Objects
}  // namespace Atlas

#endif