// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubRouterId_custom.h file.

#ifndef STUB_COMMON_ROUTERID_H
#define STUB_COMMON_ROUTERID_H

#include "common/RouterId.h"
#include "stubRouterId_custom.h"

#ifndef STUB_RouterId_RouterId
//#define STUB_RouterId_RouterId
   RouterId::RouterId(long intId)
  {
    
  }
#endif //STUB_RouterId_RouterId

#ifndef STUB_RouterId_RouterId
//#define STUB_RouterId_RouterId
   RouterId::RouterId(std::string id)
  {
    
  }
#endif //STUB_RouterId_RouterId

#ifndef STUB_RouterId_RouterId
//#define STUB_RouterId_RouterId
   RouterId::RouterId(std::string id, long intId)
  {
    
  }
#endif //STUB_RouterId_RouterId


#endif