// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubAtlasFileLoader_custom.h file.

#include "common/AtlasFileLoader.h"
#include "stubAtlasFileLoader_custom.h"

#ifndef STUB_COMMON_ATLASFILELOADER_H
#define STUB_COMMON_ATLASFILELOADER_H

#ifndef STUB_AtlasFileLoader_objectArrived
//#define STUB_AtlasFileLoader_objectArrived
  void AtlasFileLoader::objectArrived(const Atlas::Objects::Root & obj)
  {
    
  }
#endif //STUB_AtlasFileLoader_objectArrived

#ifndef STUB_AtlasFileLoader_AtlasFileLoader
//#define STUB_AtlasFileLoader_AtlasFileLoader
   AtlasFileLoader::AtlasFileLoader(const std::string & filename, std::map<std::string, Atlas::Objects::Root> & m)
    : Atlas::Objects::ObjectsDecoder(filename, m)
    , m_codec(nullptr)
  {
    
  }
#endif //STUB_AtlasFileLoader_AtlasFileLoader

#ifndef STUB_AtlasFileLoader_AtlasFileLoader_DTOR
//#define STUB_AtlasFileLoader_AtlasFileLoader_DTOR
   AtlasFileLoader::~AtlasFileLoader()
  {
    
  }
#endif //STUB_AtlasFileLoader_AtlasFileLoader_DTOR

#ifndef STUB_AtlasFileLoader_isOpen
//#define STUB_AtlasFileLoader_isOpen
  bool AtlasFileLoader::isOpen()
  {
    return false;
  }
#endif //STUB_AtlasFileLoader_isOpen

#ifndef STUB_AtlasFileLoader_read
//#define STUB_AtlasFileLoader_read
  void AtlasFileLoader::read()
  {
    
  }
#endif //STUB_AtlasFileLoader_read


#endif