// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubsystem_custom.h file.

#include "common/system.h"
#include "stubsystem_custom.h"

#ifndef STUB_COMMON_SYSTEM_H
#define STUB_COMMON_SYSTEM_H

#endif