// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubcustom_custom.h file.

#include "common/custom.h"
#include "stubcustom_custom.h"

#ifndef STUB_COMMON_CUSTOM_H
#define STUB_COMMON_CUSTOM_H

#endif