// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubChange_custom.h file.

#include "common/Change.h"
#include "stubChange_custom.h"

#ifndef STUB_COMMON_CHANGE_H
#define STUB_COMMON_CHANGE_H

namespace Atlas {
namespace Objects {
namespace Operation {


}  // namespace Operation
}  // namespace Objects
}  // namespace Atlas

#endif