// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCommAsioClient_impl_custom.h file.

#ifndef STUB_COMMON_COMMASIOCLIENT_IMPL_H
#define STUB_COMMON_COMMASIOCLIENT_IMPL_H

#include "common/CommAsioClient_impl.h"
#include "stubCommAsioClient_impl_custom.h"

#endif