// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubAffect_custom.h file.

#include "common/Affect.h"
#include "stubAffect_custom.h"

#ifndef STUB_COMMON_AFFECT_H
#define STUB_COMMON_AFFECT_H

#endif