// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubTypeStore_custom.h file.

#ifndef STUB_COMMON_TYPESTORE_H
#define STUB_COMMON_TYPESTORE_H

#include "common/TypeStore.h"
#include "stubTypeStore_custom.h"

#ifndef STUB_TypeStore_getType
//#define STUB_TypeStore_getType
  const TypeNode* TypeStore::getType(const std::string& parent) const
  {
    return nullptr;
  }
#endif //STUB_TypeStore_getType

#ifndef STUB_TypeStore_addChild
//#define STUB_TypeStore_addChild
  TypeNode* TypeStore::addChild(const Atlas::Objects::Root & obj)
  {
    return nullptr;
  }
#endif //STUB_TypeStore_addChild


#endif