// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubop_switch_custom.h file.

#include "common/op_switch.h"
#include "stubop_switch_custom.h"

#ifndef STUB_COMMON_OP_SWITCH_H
#define STUB_COMMON_OP_SWITCH_H

#endif