// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPython_API_custom.h file.

#ifndef STUB_PYTHONBASE_PYTHON_API_H
#define STUB_PYTHONBASE_PYTHON_API_H

#include "pythonbase/Python_API.h"
#include "stubPython_API_custom.h"


#endif