// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPythonClass_custom.h file.

#ifndef STUB_PYTHONBASE_PYTHONCLASS_H
#define STUB_PYTHONBASE_PYTHONCLASS_H

#include "pythonbase/PythonClass.h"
#include "stubPythonClass_custom.h"

#ifndef STUB_PythonClass_PythonClass
//#define STUB_PythonClass_PythonClass
   PythonClass::PythonClass(const std::string& package, const std::string& type)
  {
    
  }
#endif //STUB_PythonClass_PythonClass

#ifndef STUB_PythonClass_getClass
//#define STUB_PythonClass_getClass
  int PythonClass::getClass(const Py::Module& module)
  {
    return 0;
  }
#endif //STUB_PythonClass_getClass

#ifndef STUB_PythonClass_load
//#define STUB_PythonClass_load
  int PythonClass::load()
  {
    return 0;
  }
#endif //STUB_PythonClass_load

#ifndef STUB_PythonClass_refresh
//#define STUB_PythonClass_refresh
  int PythonClass::refresh()
  {
    return 0;
  }
#endif //STUB_PythonClass_refresh

#ifndef STUB_PythonClass_PythonClass_DTOR
//#define STUB_PythonClass_PythonClass_DTOR
   PythonClass::~PythonClass()
  {
    
  }
#endif //STUB_PythonClass_PythonClass_DTOR


#endif