#This file is auto generated by the PythonDocGenerator tool. Please do not edit manually.
#Its sole purpose is to provide Python stubs for the C++ code, which can be used in your IDE to help during development.
#Do note that these types aren't complete, with constructor args and properties missing.
"""Physics"""

class BBox:
    def __init__(self, *args, **kwargs):
        pass
    def as_sequence(self):
        pass
    def square_bounding_radius(self):
        pass
    def square_horizontal_bounding_radius(self):
        pass

class Ball:
    def __init__(self, *args, **kwargs):
        pass

class Point3D:
    def __init__(self, *args, **kwargs):
        pass
    def distance(self):
        pass
    def is_valid(self):
        pass
    def mag(self):
        pass
    def unit_vector_to(self):
        pass

class Quaternion:
    def __init__(self, *args, **kwargs):
        pass
    def as_list(self):
        pass
    def is_valid(self):
        pass
    def rotation(self):
        pass

class Vector3D:
    def __init__(self, *args, **kwargs):
        pass
    def angle(self):
        pass
    def cross(self):
        pass
    def dot(self):
        pass
    def is_valid(self):
        pass
    def mag(self):
        pass
    def normalize(self):
        pass
    def rotate(self):
        pass
    def rotatex(self):
        pass
    def rotatey(self):
        pass
    def rotatez(self):
        pass
    def sqr_mag(self):
        pass
    def unit_vector(self):
        pass
    def unit_vector_to(self):
        pass

