#This file is auto generated by the PythonDocGenerator tool. Please do not edit manually.
#Its sole purpose is to provide Python stubs for the C++ code, which can be used in your IDE to help during development.
#Do note that these types aren't complete, with constructor args and properties missing.
"""Rules"""

def extract_location():
    """Extracts all location data from the entity into the root entity message."""
    pass
def isLocation():
    pass
class EntityLocation:
    def __init__(self, *args, **kwargs):
        pass
    def copy(self):
        pass

class Location:
    def __init__(self, *args, **kwargs):
        pass
    def add_to_entity(self):
        """Adds the location data to the supplied entity and return the entity."""
        pass
    def copy(self):
        pass

