// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_MemMap_custom.h file.

#ifndef STUB_RULES_AI_PYTHON_CYPY_MEMMAP_H
#define STUB_RULES_AI_PYTHON_CYPY_MEMMAP_H

#include "rules/ai/python/CyPy_MemMap.h"
#include "stubCyPy_MemMap_custom.h"

#ifndef STUB_CyPy_MemMap_CyPy_MemMap
//#define STUB_CyPy_MemMap_CyPy_MemMap
   CyPy_MemMap::CyPy_MemMap(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : WrapperBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_MemMap_CyPy_MemMap

#ifndef STUB_CyPy_MemMap_CyPy_MemMap
//#define STUB_CyPy_MemMap_CyPy_MemMap
   CyPy_MemMap::CyPy_MemMap(Py::PythonClassInstance* self, MemMap* value)
    : WrapperBase(self, value)
  {
    
  }
#endif //STUB_CyPy_MemMap_CyPy_MemMap

#ifndef STUB_CyPy_MemMap_init_type
//#define STUB_CyPy_MemMap_init_type
   void CyPy_MemMap::init_type()
  {
    
  }
#endif //STUB_CyPy_MemMap_init_type

#ifndef STUB_CyPy_MemMap_find_by_location
//#define STUB_CyPy_MemMap_find_by_location
  Py::Object CyPy_MemMap::find_by_location(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_find_by_location

#ifndef STUB_CyPy_MemMap_find_by_type
//#define STUB_CyPy_MemMap_find_by_type
  Py::Object CyPy_MemMap::find_by_type(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_find_by_type

#ifndef STUB_CyPy_MemMap_updateAdd
//#define STUB_CyPy_MemMap_updateAdd
  Py::Object CyPy_MemMap::updateAdd(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_updateAdd

#ifndef STUB_CyPy_MemMap_delete_
//#define STUB_CyPy_MemMap_delete_
  Py::Object CyPy_MemMap::delete_(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_delete_

#ifndef STUB_CyPy_MemMap_get
//#define STUB_CyPy_MemMap_get
  Py::Object CyPy_MemMap::get(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_get

#ifndef STUB_CyPy_MemMap_get_all
//#define STUB_CyPy_MemMap_get_all
  Py::Object CyPy_MemMap::get_all()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_get_all

#ifndef STUB_CyPy_MemMap_get_add
//#define STUB_CyPy_MemMap_get_add
  Py::Object CyPy_MemMap::get_add(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_get_add

#ifndef STUB_CyPy_MemMap_find_by_filter
//#define STUB_CyPy_MemMap_find_by_filter
  Py::Object CyPy_MemMap::find_by_filter(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_find_by_filter

#ifndef STUB_CyPy_MemMap_find_by_location_query
//#define STUB_CyPy_MemMap_find_by_location_query
  Py::Object CyPy_MemMap::find_by_location_query(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_find_by_location_query

#ifndef STUB_CyPy_MemMap_add_entity_memory
//#define STUB_CyPy_MemMap_add_entity_memory
  Py::Object CyPy_MemMap::add_entity_memory(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_add_entity_memory

#ifndef STUB_CyPy_MemMap_remove_entity_memory
//#define STUB_CyPy_MemMap_remove_entity_memory
  Py::Object CyPy_MemMap::remove_entity_memory(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_remove_entity_memory

#ifndef STUB_CyPy_MemMap_recall_entity_memory
//#define STUB_CyPy_MemMap_recall_entity_memory
  Py::Object CyPy_MemMap::recall_entity_memory(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_recall_entity_memory

#ifndef STUB_CyPy_MemMap_createFilterContext
//#define STUB_CyPy_MemMap_createFilterContext
   EntityFilter::QueryContext CyPy_MemMap::createFilterContext(LocatedEntity* entity, MemMap* memMap)
  {
    return *static_cast< EntityFilter::QueryContext*>(nullptr);
  }
#endif //STUB_CyPy_MemMap_createFilterContext


#endif