// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubEntityProperty_custom.h file.

#include "rulesets/EntityProperty.h"
#include "stubEntityProperty_custom.h"

#ifndef STUB_RULESETS_ENTITYPROPERTY_H
#define STUB_RULESETS_ENTITYPROPERTY_H

#ifndef STUB_EntityProperty_EntityProperty
//#define STUB_EntityProperty_EntityProperty
   EntityProperty::EntityProperty()
    : PropertyBase()
  {
    
  }
#endif //STUB_EntityProperty_EntityProperty

#ifndef STUB_EntityProperty_get
//#define STUB_EntityProperty_get
  int EntityProperty::get(Atlas::Message::Element & val) const
  {
    return 0;
  }
#endif //STUB_EntityProperty_get

#ifndef STUB_EntityProperty_set
//#define STUB_EntityProperty_set
  void EntityProperty::set(const Atlas::Message::Element & val)
  {
    
  }
#endif //STUB_EntityProperty_set

#ifndef STUB_EntityProperty_add
//#define STUB_EntityProperty_add
  void EntityProperty::add(const std::string & val, Atlas::Message::MapType & map) const
  {
    
  }
#endif //STUB_EntityProperty_add

#ifndef STUB_EntityProperty_add
//#define STUB_EntityProperty_add
  void EntityProperty::add(const std::string & val, const Atlas::Objects::Entity::RootEntity & ent) const
  {
    
  }
#endif //STUB_EntityProperty_add

#ifndef STUB_EntityProperty_copy
//#define STUB_EntityProperty_copy
  EntityProperty* EntityProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_EntityProperty_copy


#endif