// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubQuaternionProperty_custom.h file.

#include "rulesets/QuaternionProperty.h"
#include "stubQuaternionProperty_custom.h"

#ifndef STUB_RULESETS_QUATERNIONPROPERTY_H
#define STUB_RULESETS_QUATERNIONPROPERTY_H

#ifndef STUB_QuaternionProperty_QuaternionProperty
//#define STUB_QuaternionProperty_QuaternionProperty
   QuaternionProperty::QuaternionProperty()
    : PropertyBase()
  {
    
  }
#endif //STUB_QuaternionProperty_QuaternionProperty

#ifndef STUB_QuaternionProperty_QuaternionProperty
//#define STUB_QuaternionProperty_QuaternionProperty
   QuaternionProperty::QuaternionProperty(const QuaternionProperty& rhs)
    : PropertyBase(rhs)
  {
    
  }
#endif //STUB_QuaternionProperty_QuaternionProperty

#ifndef STUB_QuaternionProperty_QuaternionProperty_DTOR
//#define STUB_QuaternionProperty_QuaternionProperty_DTOR
   QuaternionProperty::~QuaternionProperty()
  {
    
  }
#endif //STUB_QuaternionProperty_QuaternionProperty_DTOR

#ifndef STUB_QuaternionProperty_get
//#define STUB_QuaternionProperty_get
  int QuaternionProperty::get(Atlas::Message::Element & val) const
  {
    return 0;
  }
#endif //STUB_QuaternionProperty_get

#ifndef STUB_QuaternionProperty_set
//#define STUB_QuaternionProperty_set
  void QuaternionProperty::set(const Atlas::Message::Element &)
  {
    
  }
#endif //STUB_QuaternionProperty_set

#ifndef STUB_QuaternionProperty_copy
//#define STUB_QuaternionProperty_copy
  QuaternionProperty* QuaternionProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_QuaternionProperty_copy


#endif