// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubBBoxProperty_custom.h file.

#include "rulesets/BBoxProperty.h"
#include "stubBBoxProperty_custom.h"

#ifndef STUB_RULESETS_BBOXPROPERTY_H
#define STUB_RULESETS_BBOXPROPERTY_H

#ifndef STUB_BBoxProperty_BBoxProperty
//#define STUB_BBoxProperty_BBoxProperty
   BBoxProperty::BBoxProperty()
    : PropertyBase()
  {
    
  }
#endif //STUB_BBoxProperty_BBoxProperty

#ifndef STUB_BBoxProperty_apply
//#define STUB_BBoxProperty_apply
  void BBoxProperty::apply(LocatedEntity *)
  {
    
  }
#endif //STUB_BBoxProperty_apply

#ifndef STUB_BBoxProperty_get
//#define STUB_BBoxProperty_get
  int BBoxProperty::get(Atlas::Message::Element & val) const
  {
    return 0;
  }
#endif //STUB_BBoxProperty_get

#ifndef STUB_BBoxProperty_set
//#define STUB_BBoxProperty_set
  void BBoxProperty::set(const Atlas::Message::Element & val)
  {
    
  }
#endif //STUB_BBoxProperty_set

#ifndef STUB_BBoxProperty_add
//#define STUB_BBoxProperty_add
  void BBoxProperty::add(const std::string & key, Atlas::Message::MapType & map) const
  {
    
  }
#endif //STUB_BBoxProperty_add

#ifndef STUB_BBoxProperty_add
//#define STUB_BBoxProperty_add
  void BBoxProperty::add(const std::string & key, const Atlas::Objects::Entity::RootEntity & ent) const
  {
    
  }
#endif //STUB_BBoxProperty_add

#ifndef STUB_BBoxProperty_copy
//#define STUB_BBoxProperty_copy
  BBoxProperty* BBoxProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_BBoxProperty_copy


#endif