// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_Props_custom.h file.

#ifndef STUB_RULESETS_CYPY_PROPS_H
#define STUB_RULESETS_CYPY_PROPS_H

#include "rulesets/CyPy_Props.h"
#include "stubCyPy_Props_custom.h"

#endif