// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubSpawnProperty_custom.h file.

#include "rulesets/SpawnProperty.h"
#include "stubSpawnProperty_custom.h"

#ifndef STUB_RULESETS_SPAWNPROPERTY_H
#define STUB_RULESETS_SPAWNPROPERTY_H

#ifndef STUB_SpawnProperty_SpawnProperty
//#define STUB_SpawnProperty_SpawnProperty
   SpawnProperty::SpawnProperty()
    : Property()
  {
    
  }
#endif //STUB_SpawnProperty_SpawnProperty

#ifndef STUB_SpawnProperty_SpawnProperty_DTOR
//#define STUB_SpawnProperty_SpawnProperty_DTOR
   SpawnProperty::~SpawnProperty()
  {
    
  }
#endif //STUB_SpawnProperty_SpawnProperty_DTOR

#ifndef STUB_SpawnProperty_copy
//#define STUB_SpawnProperty_copy
  SpawnProperty* SpawnProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_SpawnProperty_copy

#ifndef STUB_SpawnProperty_apply
//#define STUB_SpawnProperty_apply
  void SpawnProperty::apply(LocatedEntity *)
  {
    
  }
#endif //STUB_SpawnProperty_apply

#ifndef STUB_SpawnProperty_remove
//#define STUB_SpawnProperty_remove
  void SpawnProperty::remove(LocatedEntity *, const std::string&)
  {
    
  }
#endif //STUB_SpawnProperty_remove


#endif