// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubStatisticsProperty_custom.h file.

#include "rulesets/StatisticsProperty.h"
#include "stubStatisticsProperty_custom.h"

#ifndef STUB_RULESETS_STATISTICSPROPERTY_H
#define STUB_RULESETS_STATISTICSPROPERTY_H

#ifndef STUB_StatisticsProperty_StatisticsProperty
//#define STUB_StatisticsProperty_StatisticsProperty
   StatisticsProperty::StatisticsProperty(const StatisticsProperty &)
    : PropertyBase(StatisticsProperty)
  {
    
  }
#endif //STUB_StatisticsProperty_StatisticsProperty

#ifndef STUB_StatisticsProperty_StatisticsProperty
//#define STUB_StatisticsProperty_StatisticsProperty
   StatisticsProperty::StatisticsProperty()
    : PropertyBase()
  {
    
  }
#endif //STUB_StatisticsProperty_StatisticsProperty

#ifndef STUB_StatisticsProperty_StatisticsProperty_DTOR
//#define STUB_StatisticsProperty_StatisticsProperty_DTOR
   StatisticsProperty::~StatisticsProperty()
  {
    
  }
#endif //STUB_StatisticsProperty_StatisticsProperty_DTOR

#ifndef STUB_StatisticsProperty_install
//#define STUB_StatisticsProperty_install
  void StatisticsProperty::install(LocatedEntity *, const std::string &)
  {
    
  }
#endif //STUB_StatisticsProperty_install

#ifndef STUB_StatisticsProperty_apply
//#define STUB_StatisticsProperty_apply
  void StatisticsProperty::apply(LocatedEntity *)
  {
    
  }
#endif //STUB_StatisticsProperty_apply

#ifndef STUB_StatisticsProperty_get
//#define STUB_StatisticsProperty_get
  int StatisticsProperty::get(Atlas::Message::Element &) const
  {
    return 0;
  }
#endif //STUB_StatisticsProperty_get

#ifndef STUB_StatisticsProperty_set
//#define STUB_StatisticsProperty_set
  void StatisticsProperty::set(const Atlas::Message::Element &)
  {
    
  }
#endif //STUB_StatisticsProperty_set

#ifndef STUB_StatisticsProperty_copy
//#define STUB_StatisticsProperty_copy
  StatisticsProperty* StatisticsProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_StatisticsProperty_copy

#ifndef STUB_StatisticsProperty_getStat
//#define STUB_StatisticsProperty_getStat
  bool StatisticsProperty::getStat(const std::string & name, double & val) const
  {
    return false;
  }
#endif //STUB_StatisticsProperty_getStat


#endif