// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubGeometryProperty_custom.h file.

#include "rulesets/GeometryProperty.h"
#include "stubGeometryProperty_custom.h"

#ifndef STUB_RULESETS_GEOMETRYPROPERTY_H
#define STUB_RULESETS_GEOMETRYPROPERTY_H

#ifndef STUB_GeometryProperty_GeometryProperty
//#define STUB_GeometryProperty_GeometryProperty
   GeometryProperty::GeometryProperty()
    : Property()
  {
    
  }
#endif //STUB_GeometryProperty_GeometryProperty

#ifndef STUB_GeometryProperty_GeometryProperty_DTOR
//#define STUB_GeometryProperty_GeometryProperty_DTOR
   GeometryProperty::~GeometryProperty()
  {
    
  }
#endif //STUB_GeometryProperty_GeometryProperty_DTOR

#ifndef STUB_GeometryProperty_set
//#define STUB_GeometryProperty_set
  void GeometryProperty::set(const Atlas::Message::Element&)
  {
    
  }
#endif //STUB_GeometryProperty_set

#ifndef STUB_GeometryProperty_copy
//#define STUB_GeometryProperty_copy
  GeometryProperty* GeometryProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_GeometryProperty_copy

#ifndef STUB_GeometryProperty_createShape
//#define STUB_GeometryProperty_createShape
  std::pair<btCollisionShape*, std::shared_ptr<btCollisionShape>> GeometryProperty::createShape(const WFMath::AxisBox<3>& bbox, btVector3& centerOfMassOffset) const
  {
    return *static_cast<std::pair<btCollisionShape*, std::shared_ptr<btCollisionShape>>*>(nullptr);
  }
#endif //STUB_GeometryProperty_createShape

#ifndef STUB_GeometryProperty_buildMeshCreator
//#define STUB_GeometryProperty_buildMeshCreator
  void GeometryProperty::buildMeshCreator()
  {
    
  }
#endif //STUB_GeometryProperty_buildMeshCreator


#endif