// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubBiomassProperty_custom.h file.

#include "rulesets/BiomassProperty.h"
#include "stubBiomassProperty_custom.h"

#ifndef STUB_RULESETS_BIOMASSPROPERTY_H
#define STUB_RULESETS_BIOMASSPROPERTY_H

#ifndef STUB_BiomassProperty_install
//#define STUB_BiomassProperty_install
  void BiomassProperty::install(LocatedEntity *, const std::string &)
  {
    
  }
#endif //STUB_BiomassProperty_install

#ifndef STUB_BiomassProperty_remove
//#define STUB_BiomassProperty_remove
  void BiomassProperty::remove(LocatedEntity *, const std::string &)
  {
    
  }
#endif //STUB_BiomassProperty_remove

#ifndef STUB_BiomassProperty_operation
//#define STUB_BiomassProperty_operation
  HandlerResult BiomassProperty::operation(LocatedEntity *, const Operation &, OpVector &)
  {
    return *static_cast<HandlerResult*>(nullptr);
  }
#endif //STUB_BiomassProperty_operation

#ifndef STUB_BiomassProperty_copy
//#define STUB_BiomassProperty_copy
  BiomassProperty* BiomassProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_BiomassProperty_copy

#ifndef STUB_BiomassProperty_eat_handler
//#define STUB_BiomassProperty_eat_handler
  HandlerResult BiomassProperty::eat_handler(LocatedEntity * e, const Operation & op, OpVector & res)
  {
    return *static_cast<HandlerResult*>(nullptr);
  }
#endif //STUB_BiomassProperty_eat_handler


#endif