// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPy_Operation_custom.h file.

#ifndef STUB_RULESETS_PY_OPERATION_H
#define STUB_RULESETS_PY_OPERATION_H

#include "rulesets/Py_Operation.h"
#include "stubPy_Operation_custom.h"

#endif