// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubAngularFactorProperty_custom.h file.

#include "rulesets/AngularFactorProperty.h"
#include "stubAngularFactorProperty_custom.h"

#ifndef STUB_RULESETS_ANGULARFACTORPROPERTY_H
#define STUB_RULESETS_ANGULARFACTORPROPERTY_H

#ifndef STUB_AngularFactorProperty_copy
//#define STUB_AngularFactorProperty_copy
  AngularFactorProperty* AngularFactorProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_AngularFactorProperty_copy

#ifndef STUB_AngularFactorProperty_get
//#define STUB_AngularFactorProperty_get
  int AngularFactorProperty::get(Atlas::Message::Element & val) const
  {
    return 0;
  }
#endif //STUB_AngularFactorProperty_get

#ifndef STUB_AngularFactorProperty_set
//#define STUB_AngularFactorProperty_set
  void AngularFactorProperty::set(const Atlas::Message::Element & val)
  {
    
  }
#endif //STUB_AngularFactorProperty_set

#ifndef STUB_AngularFactorProperty_add
//#define STUB_AngularFactorProperty_add
  void AngularFactorProperty::add(const std::string & key, Atlas::Message::MapType & map) const
  {
    
  }
#endif //STUB_AngularFactorProperty_add

#ifndef STUB_AngularFactorProperty_add
//#define STUB_AngularFactorProperty_add
  void AngularFactorProperty::add(const std::string & key, const Atlas::Objects::Entity::RootEntity & ent) const
  {
    
  }
#endif //STUB_AngularFactorProperty_add


#endif