// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubDefaultLocationProperty_custom.h file.

#include "rulesets/DefaultLocationProperty.h"
#include "stubDefaultLocationProperty_custom.h"

#ifndef STUB_RULESETS_DEFAULTLOCATIONPROPERTY_H
#define STUB_RULESETS_DEFAULTLOCATIONPROPERTY_H

#ifndef STUB_DefaultLocationProperty_DefaultLocationProperty
//#define STUB_DefaultLocationProperty_DefaultLocationProperty
   DefaultLocationProperty::DefaultLocationProperty()
    : Property()
  {
    
  }
#endif //STUB_DefaultLocationProperty_DefaultLocationProperty

#ifndef STUB_DefaultLocationProperty_copy
//#define STUB_DefaultLocationProperty_copy
  DefaultLocationProperty* DefaultLocationProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_DefaultLocationProperty_copy

#ifndef STUB_DefaultLocationProperty_install
//#define STUB_DefaultLocationProperty_install
  void DefaultLocationProperty::install(LocatedEntity *, const std::string &)
  {
    
  }
#endif //STUB_DefaultLocationProperty_install

#ifndef STUB_DefaultLocationProperty_remove
//#define STUB_DefaultLocationProperty_remove
  void DefaultLocationProperty::remove(LocatedEntity *, const std::string &)
  {
    
  }
#endif //STUB_DefaultLocationProperty_remove


#endif