// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubSpawnerProperty_custom.h file.

#include "rulesets/SpawnerProperty.h"
#include "stubSpawnerProperty_custom.h"

#ifndef STUB_RULESETS_SPAWNERPROPERTY_H
#define STUB_RULESETS_SPAWNERPROPERTY_H

#ifndef STUB_SpawnerProperty_SpawnerProperty
//#define STUB_SpawnerProperty_SpawnerProperty
   SpawnerProperty::SpawnerProperty()
    : Property()
  {
    
  }
#endif //STUB_SpawnerProperty_SpawnerProperty

#ifndef STUB_SpawnerProperty_SpawnerProperty_DTOR
//#define STUB_SpawnerProperty_SpawnerProperty_DTOR
   SpawnerProperty::~SpawnerProperty()
  {
    
  }
#endif //STUB_SpawnerProperty_SpawnerProperty_DTOR

#ifndef STUB_SpawnerProperty_install
//#define STUB_SpawnerProperty_install
  void SpawnerProperty::install(LocatedEntity *, const std::string &)
  {
    
  }
#endif //STUB_SpawnerProperty_install

#ifndef STUB_SpawnerProperty_remove
//#define STUB_SpawnerProperty_remove
  void SpawnerProperty::remove(LocatedEntity *, const std::string &)
  {
    
  }
#endif //STUB_SpawnerProperty_remove

#ifndef STUB_SpawnerProperty_apply
//#define STUB_SpawnerProperty_apply
  void SpawnerProperty::apply(LocatedEntity *)
  {
    
  }
#endif //STUB_SpawnerProperty_apply

#ifndef STUB_SpawnerProperty_operation
//#define STUB_SpawnerProperty_operation
  HandlerResult SpawnerProperty::operation(LocatedEntity *, const Operation &, OpVector &)
  {
    return *static_cast<HandlerResult*>(nullptr);
  }
#endif //STUB_SpawnerProperty_operation

#ifndef STUB_SpawnerProperty_copy
//#define STUB_SpawnerProperty_copy
  SpawnerProperty* SpawnerProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_SpawnerProperty_copy

#ifndef STUB_SpawnerProperty_tick_handler
//#define STUB_SpawnerProperty_tick_handler
  HandlerResult SpawnerProperty::tick_handler(LocatedEntity * e, const Operation & op, OpVector & res)
  {
    return *static_cast<HandlerResult*>(nullptr);
  }
#endif //STUB_SpawnerProperty_tick_handler

#ifndef STUB_SpawnerProperty_createTickOp
//#define STUB_SpawnerProperty_createTickOp
  Atlas::Objects::Operation::RootOperation SpawnerProperty::createTickOp()
  {
    return *static_cast<Atlas::Objects::Operation::RootOperation*>(nullptr);
  }
#endif //STUB_SpawnerProperty_createTickOp

#ifndef STUB_SpawnerProperty_handleTick
//#define STUB_SpawnerProperty_handleTick
  void SpawnerProperty::handleTick(LocatedEntity * e, const Operation & op, OpVector & res)
  {
    
  }
#endif //STUB_SpawnerProperty_handleTick

#ifndef STUB_SpawnerProperty_createNewEntity
//#define STUB_SpawnerProperty_createNewEntity
  void SpawnerProperty::createNewEntity(LocatedEntity * e, const Operation & op, OpVector & res, const std::string& locId)
  {
    
  }
#endif //STUB_SpawnerProperty_createNewEntity


#endif