// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPy_Message_custom.h file.

#include "rulesets/Py_Message.h"
#include "stubPy_Message_custom.h"

#ifndef STUB_RULESETS_PY_MESSAGE_H
#define STUB_RULESETS_PY_MESSAGE_H

#endif