// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubVisibilityProperty_custom.h file.

#include "rulesets/VisibilityProperty.h"
#include "stubVisibilityProperty_custom.h"

#ifndef STUB_RULESETS_VISIBILITYPROPERTY_H
#define STUB_RULESETS_VISIBILITYPROPERTY_H

#ifndef STUB_VisibilityProperty_copy
//#define STUB_VisibilityProperty_copy
  VisibilityProperty* VisibilityProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_VisibilityProperty_copy


#endif