// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubLimbo_custom.h file.

#include "rulesets/Limbo.h"
#include "stubLimbo_custom.h"

#ifndef STUB_RULESETS_LIMBO_H
#define STUB_RULESETS_LIMBO_H

#ifndef STUB_Limbo_Limbo
//#define STUB_Limbo_Limbo
   Limbo::Limbo(const std::string & id, long intId)
    : Thing(id, intId)
  {
    
  }
#endif //STUB_Limbo_Limbo

#ifndef STUB_Limbo_Limbo_DTOR
//#define STUB_Limbo_Limbo_DTOR
   Limbo::~Limbo()
  {
    
  }
#endif //STUB_Limbo_Limbo_DTOR

#ifndef STUB_Limbo_addChild
//#define STUB_Limbo_addChild
  void Limbo::addChild(LocatedEntity& childEntity)
  {
    
  }
#endif //STUB_Limbo_addChild


#endif