// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubEntityPropertyFactory_impl_custom.h file.

#include "rulesets/EntityPropertyFactory_impl.h"
#include "stubEntityPropertyFactory_impl_custom.h"

#ifndef STUB_RULESETS_ENTITYPROPERTYFACTORY_IMPL_H
#define STUB_RULESETS_ENTITYPROPERTYFACTORY_IMPL_H

#endif