// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPhysicalWorld_custom.h file.

#include "rulesets/PhysicalWorld.h"
#include "stubPhysicalWorld_custom.h"

#ifndef STUB_RULESETS_PHYSICALWORLD_H
#define STUB_RULESETS_PHYSICALWORLD_H

#ifndef STUB_PhysicalWorld_PhysicalWorld
//#define STUB_PhysicalWorld_PhysicalWorld
   PhysicalWorld::PhysicalWorld(btDispatcher* dispatcher, btBroadphaseInterface* pairCache, btConstraintSolver* constraintSolver, btCollisionConfiguration* collisionConfiguration)
    : btDiscreteDynamicsWorld(dispatcher, pairCache, constraintSolver, collisionConfiguration)
  {
    
  }
#endif //STUB_PhysicalWorld_PhysicalWorld

#ifndef STUB_PhysicalWorld_synchronizeMotionStates
//#define STUB_PhysicalWorld_synchronizeMotionStates
  void PhysicalWorld::synchronizeMotionStates()
  {
    
  }
#endif //STUB_PhysicalWorld_synchronizeMotionStates

#ifndef STUB_PhysicalWorld_stepSimulation
//#define STUB_PhysicalWorld_stepSimulation
  int PhysicalWorld::stepSimulation(btScalar timeStep, int maxSubSteps , btScalar fixedTimeStep )
  {
    return 0;
  }
#endif //STUB_PhysicalWorld_stepSimulation


#endif