// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPy_WorldTime_custom.h file.

#include "rulesets/Py_WorldTime.h"
#include "stubPy_WorldTime_custom.h"

#ifndef STUB_RULESETS_PY_WORLDTIME_H
#define STUB_RULESETS_PY_WORLDTIME_H

#endif