// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubScript_custom.h file.

#ifndef STUB_RULESETS_SCRIPT_H
#define STUB_RULESETS_SCRIPT_H

#include "rulesets/Script.h"
#include "stubScript_custom.h"

#ifndef STUB_Script_operation
//#define STUB_Script_operation
  HandlerResult Script::operation(const std::string & opname, const Atlas::Objects::Operation::RootOperation & op, OpVector & res)
  {
    return *static_cast<HandlerResult*>(nullptr);
  }
#endif //STUB_Script_operation

#ifndef STUB_Script_hook
//#define STUB_Script_hook
  void Script::hook(const std::string & function, LocatedEntity * entity)
  {
    
  }
#endif //STUB_Script_hook


#endif