// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubDomain_custom.h file.

#include "rulesets/Domain.h"
#include "stubDomain_custom.h"

#ifndef STUB_RULESETS_DOMAIN_H
#define STUB_RULESETS_DOMAIN_H

#ifndef STUB_Domain_Domain
//#define STUB_Domain_Domain
   Domain::Domain(LocatedEntity& entity)
  {
    
  }
#endif //STUB_Domain_Domain

#ifndef STUB_Domain_Domain_DTOR
//#define STUB_Domain_Domain_DTOR
   Domain::~Domain()
  {
    
  }
#endif //STUB_Domain_Domain_DTOR

#ifndef STUB_Domain_tick
//#define STUB_Domain_tick
  void Domain::tick(double t, OpVector& res)
  {
    
  }
#endif //STUB_Domain_tick

#ifndef STUB_Domain_isEntityVisibleFor
//#define STUB_Domain_isEntityVisibleFor
  bool Domain::isEntityVisibleFor(const LocatedEntity& observingEntity, const LocatedEntity& observedEntity) const
  {
    return false;
  }
#endif //STUB_Domain_isEntityVisibleFor

#ifndef STUB_Domain_addEntity
//#define STUB_Domain_addEntity
  void Domain::addEntity(LocatedEntity& entity)
  {
    
  }
#endif //STUB_Domain_addEntity

#ifndef STUB_Domain_removeEntity
//#define STUB_Domain_removeEntity
  void Domain::removeEntity(LocatedEntity& entity)
  {
    
  }
#endif //STUB_Domain_removeEntity

#ifndef STUB_Domain_getVisibleEntitiesFor
//#define STUB_Domain_getVisibleEntitiesFor
  void Domain::getVisibleEntitiesFor(const LocatedEntity& observingEntity, std::list<LocatedEntity*>& entityList) const
  {
    
  }
#endif //STUB_Domain_getVisibleEntitiesFor


#endif