// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPythonWrapper_custom.h file.

#include "rulesets/PythonWrapper.h"
#include "stubPythonWrapper_custom.h"

#ifndef STUB_RULESETS_PYTHONWRAPPER_H
#define STUB_RULESETS_PYTHONWRAPPER_H

#ifndef STUB_PythonWrapper_PythonWrapper
//#define STUB_PythonWrapper_PythonWrapper
   PythonWrapper::PythonWrapper(struct _object * wrapper)
    : Script(wrapper)
  {
    
  }
#endif //STUB_PythonWrapper_PythonWrapper

#ifndef STUB_PythonWrapper_PythonWrapper_DTOR
//#define STUB_PythonWrapper_PythonWrapper_DTOR
   PythonWrapper::~PythonWrapper()
  {
    
  }
#endif //STUB_PythonWrapper_PythonWrapper_DTOR


#endif