// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPy_Quaternion_custom.h file.

#include "rulesets/Py_Quaternion.h"
#include "stubPy_Quaternion_custom.h"

#ifndef STUB_RULESETS_PY_QUATERNION_H
#define STUB_RULESETS_PY_QUATERNION_H

#endif