// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubDensityProperty_custom.h file.

#include "rulesets/DensityProperty.h"
#include "stubDensityProperty_custom.h"

#ifndef STUB_RULESETS_DENSITYPROPERTY_H
#define STUB_RULESETS_DENSITYPROPERTY_H

#ifndef STUB_DensityProperty_apply
//#define STUB_DensityProperty_apply
  void DensityProperty::apply(LocatedEntity *)
  {
    
  }
#endif //STUB_DensityProperty_apply

#ifndef STUB_DensityProperty_copy
//#define STUB_DensityProperty_copy
  DensityProperty* DensityProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_DensityProperty_copy

#ifndef STUB_DensityProperty_updateMass
//#define STUB_DensityProperty_updateMass
  void DensityProperty::updateMass(LocatedEntity *entity) const
  {
    
  }
#endif //STUB_DensityProperty_updateMass


#endif