// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubScript_custom.h file.

#include "rulesets/Script.h"
#include "stubScript_custom.h"

#ifndef STUB_RULESETS_SCRIPT_H
#define STUB_RULESETS_SCRIPT_H

#ifndef STUB_Script_Script
//#define STUB_Script_Script
   Script::Script()
  {
    
  }
#endif //STUB_Script_Script

#ifndef STUB_Script_Script_DTOR
//#define STUB_Script_Script_DTOR
   Script::~Script()
  {
    
  }
#endif //STUB_Script_Script_DTOR

#ifndef STUB_Script_operation
//#define STUB_Script_operation
  bool Script::operation(const std::string & opname, const Atlas::Objects::Operation::RootOperation & op, OpVector & res)
  {
    return false;
  }
#endif //STUB_Script_operation

#ifndef STUB_Script_hook
//#define STUB_Script_hook
  void Script::hook(const std::string & function, LocatedEntity * entity)
  {
    
  }
#endif //STUB_Script_hook


#endif