// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPy_Filter_custom.h file.

#include "rulesets/Py_Filter.h"
#include "stubPy_Filter_custom.h"

#ifndef STUB_RULESETS_PY_FILTER_H
#define STUB_RULESETS_PY_FILTER_H

#endif