// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubModeProperty_custom.h file.

#include "rulesets/ModeProperty.h"
#include "stubModeProperty_custom.h"

#ifndef STUB_RULESETS_MODEPROPERTY_H
#define STUB_RULESETS_MODEPROPERTY_H

#ifndef STUB_ModeProperty_ModeProperty
//#define STUB_ModeProperty_ModeProperty
   ModeProperty::ModeProperty()
    : Property()
  {
    
  }
#endif //STUB_ModeProperty_ModeProperty

#ifndef STUB_ModeProperty_ModeProperty_DTOR
//#define STUB_ModeProperty_ModeProperty_DTOR
   ModeProperty::~ModeProperty()
  {
    
  }
#endif //STUB_ModeProperty_ModeProperty_DTOR

#ifndef STUB_ModeProperty_apply
//#define STUB_ModeProperty_apply
  void ModeProperty::apply(LocatedEntity *)
  {
    
  }
#endif //STUB_ModeProperty_apply

#ifndef STUB_ModeProperty_copy
//#define STUB_ModeProperty_copy
  ModeProperty* ModeProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_ModeProperty_copy

#ifndef STUB_ModeProperty_set
//#define STUB_ModeProperty_set
  void ModeProperty::set(const Atlas::Message::Element & val)
  {
    
  }
#endif //STUB_ModeProperty_set


#endif