// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubVector3Property_custom.h file.

#include "rulesets/Vector3Property.h"
#include "stubVector3Property_custom.h"

#ifndef STUB_RULESETS_VECTOR3PROPERTY_H
#define STUB_RULESETS_VECTOR3PROPERTY_H

#ifndef STUB_Vector3Property_Vector3Property
//#define STUB_Vector3Property_Vector3Property
   Vector3Property::Vector3Property()
    : PropertyBase()
  {
    
  }
#endif //STUB_Vector3Property_Vector3Property

#ifndef STUB_Vector3Property_Vector3Property
//#define STUB_Vector3Property_Vector3Property
   Vector3Property::Vector3Property(const Vector3Property& rhs)
    : PropertyBase(rhs)
  {
    
  }
#endif //STUB_Vector3Property_Vector3Property

#ifndef STUB_Vector3Property_Vector3Property_DTOR
//#define STUB_Vector3Property_Vector3Property_DTOR
   Vector3Property::~Vector3Property()
  {
    
  }
#endif //STUB_Vector3Property_Vector3Property_DTOR

#ifndef STUB_Vector3Property_get
//#define STUB_Vector3Property_get
  int Vector3Property::get(Atlas::Message::Element & val) const
  {
    return 0;
  }
#endif //STUB_Vector3Property_get

#ifndef STUB_Vector3Property_set
//#define STUB_Vector3Property_set
  void Vector3Property::set(const Atlas::Message::Element &)
  {
    
  }
#endif //STUB_Vector3Property_set

#ifndef STUB_Vector3Property_copy
//#define STUB_Vector3Property_copy
  Vector3Property* Vector3Property::copy() const
  {
    return nullptr;
  }
#endif //STUB_Vector3Property_copy


#endif