// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubAmountProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_AMOUNTPROPERTY_H
#define STUB_RULES_SIMULATION_AMOUNTPROPERTY_H

#include "rules/simulation/AmountProperty.h"
#include "stubAmountProperty_custom.h"

#ifndef STUB_AmountProperty_copy
//#define STUB_AmountProperty_copy
  AmountProperty* AmountProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_AmountProperty_copy

#ifndef STUB_AmountProperty_apply
//#define STUB_AmountProperty_apply
  void AmountProperty::apply(LocatedEntity& entity)
  {
    
  }
#endif //STUB_AmountProperty_apply


#endif