// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubInternalProperties_custom.h file.

#ifndef STUB_RULES_SIMULATION_INTERNALPROPERTIES_H
#define STUB_RULES_SIMULATION_INTERNALPROPERTIES_H

#include "rules/simulation/InternalProperties.h"
#include "stubInternalProperties_custom.h"

#ifndef STUB_SetupProperty_copy
//#define STUB_SetupProperty_copy
  SetupProperty* SetupProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_SetupProperty_copy

#ifndef STUB_SetupProperty_install
//#define STUB_SetupProperty_install
  void SetupProperty::install(LocatedEntity *, const std::string &)
  {
    
  }
#endif //STUB_SetupProperty_install


#ifndef STUB_TickProperty_copy
//#define STUB_TickProperty_copy
  TickProperty* TickProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_TickProperty_copy

#ifndef STUB_TickProperty_apply
//#define STUB_TickProperty_apply
  void TickProperty::apply(LocatedEntity *)
  {
    
  }
#endif //STUB_TickProperty_apply


#endif