// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubMindProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_MINDPROPERTY_H
#define STUB_RULES_SIMULATION_MINDPROPERTY_H

#include "server/MindProperty.h"
#include "stubMindProperty_custom.h"

#ifndef STUB_MindProperty_MindProperty
//#define STUB_MindProperty_MindProperty
   MindProperty::MindProperty(const MindProperty&)
    : PropertyBase(MindProperty)
  {
    
  }
#endif //STUB_MindProperty_MindProperty

#ifndef STUB_MindProperty_isMindEnabled
//#define STUB_MindProperty_isMindEnabled
  bool MindProperty::isMindEnabled() const
  {
    return false;
  }
#endif //STUB_MindProperty_isMindEnabled

#ifndef STUB_MindProperty_set
//#define STUB_MindProperty_set
  void MindProperty::set(const Atlas::Message::Element& val)
  {
    
  }
#endif //STUB_MindProperty_set

#ifndef STUB_MindProperty_get
//#define STUB_MindProperty_get
  int MindProperty::get(Atlas::Message::Element & val) const
  {
    return 0;
  }
#endif //STUB_MindProperty_get

#ifndef STUB_MindProperty_copy
//#define STUB_MindProperty_copy
  MindProperty* MindProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_MindProperty_copy

#ifndef STUB_MindProperty_apply
//#define STUB_MindProperty_apply
  void MindProperty::apply(LocatedEntity&)
  {
    
  }
#endif //STUB_MindProperty_apply


#endif