// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubContainedVisibilityProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_CONTAINEDVISIBILITYPROPERTY_H
#define STUB_RULES_SIMULATION_CONTAINEDVISIBILITYPROPERTY_H

#include "rules/simulation/ContainedVisibilityProperty.h"
#include "stubContainedVisibilityProperty_custom.h"

#ifndef STUB_ContainedVisibilityProperty_copy
//#define STUB_ContainedVisibilityProperty_copy
  ContainedVisibilityProperty* ContainedVisibilityProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_ContainedVisibilityProperty_copy

#ifndef STUB_ContainedVisibilityProperty_apply
//#define STUB_ContainedVisibilityProperty_apply
  void ContainedVisibilityProperty::apply(LocatedEntity&)
  {
    
  }
#endif //STUB_ContainedVisibilityProperty_apply

#ifndef STUB_ContainedVisibilityProperty_remove
//#define STUB_ContainedVisibilityProperty_remove
  void ContainedVisibilityProperty::remove(LocatedEntity&, const std::string&)
  {
    
  }
#endif //STUB_ContainedVisibilityProperty_remove


#endif