// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubTransientProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_TRANSIENTPROPERTY_H
#define STUB_RULES_SIMULATION_TRANSIENTPROPERTY_H

#include "rules/simulation/TransientProperty.h"
#include "stubTransientProperty_custom.h"

#ifndef STUB_TransientProperty_copy
//#define STUB_TransientProperty_copy
  TransientProperty* TransientProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_TransientProperty_copy

#ifndef STUB_TransientProperty_install
//#define STUB_TransientProperty_install
  void TransientProperty::install(LocatedEntity&, const std::string &)
  {
    
  }
#endif //STUB_TransientProperty_install

#ifndef STUB_TransientProperty_apply
//#define STUB_TransientProperty_apply
  void TransientProperty::apply(LocatedEntity&)
  {
    
  }
#endif //STUB_TransientProperty_apply


#endif