// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubDomainProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_DOMAINPROPERTY_H
#define STUB_RULES_SIMULATION_DOMAINPROPERTY_H

#include "rules/simulation/DomainProperty.h"
#include "stubDomainProperty_custom.h"

#ifndef STUB_DomainProperty_install
//#define STUB_DomainProperty_install
  void DomainProperty::install(LocatedEntity&, const std::string &)
  {
    
  }
#endif //STUB_DomainProperty_install

#ifndef STUB_DomainProperty_remove
//#define STUB_DomainProperty_remove
  void DomainProperty::remove(LocatedEntity&, const std::string &)
  {
    
  }
#endif //STUB_DomainProperty_remove

#ifndef STUB_DomainProperty_copy
//#define STUB_DomainProperty_copy
  DomainProperty* DomainProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_DomainProperty_copy

#ifndef STUB_DomainProperty_apply
//#define STUB_DomainProperty_apply
  void DomainProperty::apply(LocatedEntity&)
  {
    
  }
#endif //STUB_DomainProperty_apply

#ifndef STUB_DomainProperty_operation
//#define STUB_DomainProperty_operation
  HandlerResult DomainProperty::operation(LocatedEntity& e, const Operation & op, OpVector & res)
  {
    return *static_cast<HandlerResult*>(nullptr);
  }
#endif //STUB_DomainProperty_operation


#endif