// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubStackable_custom.h file.

#ifndef STUB_RULES_SIMULATION_STACKABLE_H
#define STUB_RULES_SIMULATION_STACKABLE_H

#include "rules/simulation/Stackable.h"
#include "stubStackable_custom.h"

#ifndef STUB_Stackable_Stackable
//#define STUB_Stackable_Stackable
   Stackable::Stackable(const std::string & id, long intId)
    : Thing(id, intId)
  {
    
  }
#endif //STUB_Stackable_Stackable

#ifndef STUB_Stackable_Stackable_DTOR
//#define STUB_Stackable_Stackable_DTOR
   Stackable::~Stackable()
  {
    
  }
#endif //STUB_Stackable_Stackable_DTOR

#ifndef STUB_Stackable_CombineOperation
//#define STUB_Stackable_CombineOperation
  void Stackable::CombineOperation(const Operation &, OpVector &)
  {
    
  }
#endif //STUB_Stackable_CombineOperation

#ifndef STUB_Stackable_DivideOperation
//#define STUB_Stackable_DivideOperation
  void Stackable::DivideOperation(const Operation &, OpVector &)
  {
    
  }
#endif //STUB_Stackable_DivideOperation


#endif