// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPlantedOnProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_PLANTEDONPROPERTY_H
#define STUB_RULES_SIMULATION_PLANTEDONPROPERTY_H

#include "rules/simulation/PlantedOnProperty.h"
#include "stubPlantedOnProperty_custom.h"

#ifndef STUB_PlantedOnProperty_get
//#define STUB_PlantedOnProperty_get
  int PlantedOnProperty::get(Atlas::Message::Element& val) const
  {
    return 0;
  }
#endif //STUB_PlantedOnProperty_get

#ifndef STUB_PlantedOnProperty_set
//#define STUB_PlantedOnProperty_set
  void PlantedOnProperty::set(const Atlas::Message::Element& val)
  {
    
  }
#endif //STUB_PlantedOnProperty_set

#ifndef STUB_PlantedOnProperty_add
//#define STUB_PlantedOnProperty_add
  void PlantedOnProperty::add(const std::string& val, Atlas::Message::MapType& map) const
  {
    
  }
#endif //STUB_PlantedOnProperty_add

#ifndef STUB_PlantedOnProperty_add
//#define STUB_PlantedOnProperty_add
  void PlantedOnProperty::add(const std::string& val, const Atlas::Objects::Entity::RootEntity& ent) const
  {
    
  }
#endif //STUB_PlantedOnProperty_add

#ifndef STUB_PlantedOnProperty_copy
//#define STUB_PlantedOnProperty_copy
  PlantedOnProperty* PlantedOnProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_PlantedOnProperty_copy

#ifndef STUB_PlantedOnProperty_data
//#define STUB_PlantedOnProperty_data
  const Data& PlantedOnProperty::data() const
  {
    return *static_cast<const Data*>(nullptr);
  }
#endif //STUB_PlantedOnProperty_data

#ifndef STUB_PlantedOnProperty_data
//#define STUB_PlantedOnProperty_data
  Data& PlantedOnProperty::data()
  {
    return *static_cast<Data*>(nullptr);
  }
#endif //STUB_PlantedOnProperty_data

#ifndef STUB_PlantedOnProperty_parse
//#define STUB_PlantedOnProperty_parse
   Data PlantedOnProperty::parse(const Atlas::Message::Element& val)
  {
    return *static_cast< Data*>(nullptr);
  }
#endif //STUB_PlantedOnProperty_parse


#endif