// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubContainerAccessProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_CONTAINERACCESSPROPERTY_H
#define STUB_RULES_SIMULATION_CONTAINERACCESSPROPERTY_H

#include "rules/simulation/ContainerAccessProperty.h"
#include "stubContainerAccessProperty_custom.h"

#ifndef STUB_ContainerAccessProperty_ContainerAccessProperty
//#define STUB_ContainerAccessProperty_ContainerAccessProperty
   ContainerAccessProperty::ContainerAccessProperty()
    : PropertyBase()
  {
    
  }
#endif //STUB_ContainerAccessProperty_ContainerAccessProperty

#ifndef STUB_ContainerAccessProperty_get
//#define STUB_ContainerAccessProperty_get
  int ContainerAccessProperty::get(Atlas::Message::Element&) const
  {
    return 0;
  }
#endif //STUB_ContainerAccessProperty_get

#ifndef STUB_ContainerAccessProperty_set
//#define STUB_ContainerAccessProperty_set
  void ContainerAccessProperty::set(const Atlas::Message::Element&)
  {
    
  }
#endif //STUB_ContainerAccessProperty_set

#ifndef STUB_ContainerAccessProperty_copy
//#define STUB_ContainerAccessProperty_copy
  ContainerAccessProperty* ContainerAccessProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_ContainerAccessProperty_copy

#ifndef STUB_ContainerAccessProperty_apply
//#define STUB_ContainerAccessProperty_apply
  void ContainerAccessProperty::apply(LocatedEntity*)
  {
    
  }
#endif //STUB_ContainerAccessProperty_apply

#ifndef STUB_ContainerAccessProperty_hasEntity
//#define STUB_ContainerAccessProperty_hasEntity
  bool ContainerAccessProperty::hasEntity(const LocatedEntity& entity) const
  {
    return false;
  }
#endif //STUB_ContainerAccessProperty_hasEntity


#endif