// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubLimboProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_LIMBOPROPERTY_H
#define STUB_RULES_SIMULATION_LIMBOPROPERTY_H

#include "rules/simulation/LimboProperty.h"
#include "stubLimboProperty_custom.h"

#ifndef STUB_LimboProperty_copy
//#define STUB_LimboProperty_copy
  LimboProperty* LimboProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_LimboProperty_copy

#ifndef STUB_LimboProperty_install
//#define STUB_LimboProperty_install
  void LimboProperty::install(LocatedEntity *, const std::string &)
  {
    
  }
#endif //STUB_LimboProperty_install

#ifndef STUB_LimboProperty_remove
//#define STUB_LimboProperty_remove
  void LimboProperty::remove(LocatedEntity *, const std::string &)
  {
    
  }
#endif //STUB_LimboProperty_remove


#endif