// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubTerrainEffectorProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_TERRAINEFFECTORPROPERTY_H
#define STUB_RULES_SIMULATION_TERRAINEFFECTORPROPERTY_H

#include "rules/simulation/TerrainEffectorProperty.h"
#include "stubTerrainEffectorProperty_custom.h"

#ifndef STUB_TerrainEffectorProperty_getTerrain
//#define STUB_TerrainEffectorProperty_getTerrain
  const TerrainProperty* TerrainEffectorProperty::getTerrain(LocatedEntity& owner, LocatedEntity** terrainHolder )
  {
    return nullptr;
  }
#endif //STUB_TerrainEffectorProperty_getTerrain


#endif