// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubFilterProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_FILTERPROPERTY_H
#define STUB_RULES_SIMULATION_FILTERPROPERTY_H

#include "rules/simulation/FilterProperty.h"
#include "stubFilterProperty_custom.h"

#ifndef STUB_FilterProperty_copy
//#define STUB_FilterProperty_copy
  FilterProperty* FilterProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_FilterProperty_copy

#ifndef STUB_FilterProperty_getData
//#define STUB_FilterProperty_getData
  const EntityFilter::Filter* FilterProperty::getData() const
  {
    return nullptr;
  }
#endif //STUB_FilterProperty_getData

#ifndef STUB_FilterProperty_get
//#define STUB_FilterProperty_get
  int FilterProperty::get(Atlas::Message::Element& val) const
  {
    return 0;
  }
#endif //STUB_FilterProperty_get

#ifndef STUB_FilterProperty_set
//#define STUB_FilterProperty_set
  void FilterProperty::set(const Atlas::Message::Element& val)
  {
    
  }
#endif //STUB_FilterProperty_set

#ifndef STUB_FilterProperty_FilterProperty
//#define STUB_FilterProperty_FilterProperty
   FilterProperty::FilterProperty(const FilterProperty& rhs)
    : PropertyBase(rhs)
  {
    
  }
#endif //STUB_FilterProperty_FilterProperty


#endif