// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubPerceptionSightProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_PERCEPTIONSIGHTPROPERTY_H
#define STUB_RULES_SIMULATION_PERCEPTIONSIGHTPROPERTY_H

#include "rules/simulation/PerceptionSightProperty.h"
#include "stubPerceptionSightProperty_custom.h"

#ifndef STUB_PerceptionSightProperty_apply
//#define STUB_PerceptionSightProperty_apply
  void PerceptionSightProperty::apply(LocatedEntity&)
  {
    
  }
#endif //STUB_PerceptionSightProperty_apply

#ifndef STUB_PerceptionSightProperty_copy
//#define STUB_PerceptionSightProperty_copy
  PerceptionSightProperty* PerceptionSightProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_PerceptionSightProperty_copy


#endif