// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubEntityCreator_custom.h file.

#ifndef STUB_RULES_SIMULATION_ENTITYCREATOR_H
#define STUB_RULES_SIMULATION_ENTITYCREATOR_H

#include "rules/simulation/EntityCreator.h"
#include "stubEntityCreator_custom.h"

#ifndef STUB_EntityCreator_newEntity
//#define STUB_EntityCreator_newEntity
  Ref<LocatedEntity> EntityCreator::newEntity(const std::string& id, long intId, const std::string& type, const Atlas::Objects::Entity::RootEntity& attrs) const
  {
    return *static_cast<Ref<LocatedEntity>*>(nullptr);
  }
#endif //STUB_EntityCreator_newEntity


#endif