// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubWorldTimeProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_WORLDTIMEPROPERTY_H
#define STUB_RULES_SIMULATION_WORLDTIMEPROPERTY_H

#include "rules/simulation/WorldTimeProperty.h"
#include "stubWorldTimeProperty_custom.h"

#ifndef STUB_WorldTimeProperty_WorldTimeProperty
//#define STUB_WorldTimeProperty_WorldTimeProperty
   WorldTimeProperty::WorldTimeProperty()
    : PropertyBase()
  {
    
  }
#endif //STUB_WorldTimeProperty_WorldTimeProperty

#ifndef STUB_WorldTimeProperty_WorldTimeProperty_DTOR
//#define STUB_WorldTimeProperty_WorldTimeProperty_DTOR
   WorldTimeProperty::~WorldTimeProperty()
  {
    
  }
#endif //STUB_WorldTimeProperty_WorldTimeProperty_DTOR

#ifndef STUB_WorldTimeProperty_copy
//#define STUB_WorldTimeProperty_copy
  WorldTimeProperty* WorldTimeProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_WorldTimeProperty_copy

#ifndef STUB_WorldTimeProperty_get
//#define STUB_WorldTimeProperty_get
  int WorldTimeProperty::get(Atlas::Message::Element& val) const
  {
    return 0;
  }
#endif //STUB_WorldTimeProperty_get

#ifndef STUB_WorldTimeProperty_set
//#define STUB_WorldTimeProperty_set
  void WorldTimeProperty::set(const Atlas::Message::Element& val)
  {
    
  }
#endif //STUB_WorldTimeProperty_set


#endif