// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubContainerAccessProperty_custom.h file.

#ifndef STUB_RULES_SIMULATION_CONTAINERACCESSPROPERTY_H
#define STUB_RULES_SIMULATION_CONTAINERACCESSPROPERTY_H

#include "rules/simulation/ContainerAccessProperty.h"
#include "stubContainerAccessProperty_custom.h"

#ifndef STUB_ContainerAccessProperty_ContainerAccessProperty
//#define STUB_ContainerAccessProperty_ContainerAccessProperty
   ContainerAccessProperty::ContainerAccessProperty(ContainerDomain& container)
    : PropertyBase(container)
  {
    
  }
#endif //STUB_ContainerAccessProperty_ContainerAccessProperty

#ifndef STUB_ContainerAccessProperty_get
//#define STUB_ContainerAccessProperty_get
  int ContainerAccessProperty::get(Atlas::Message::Element&) const
  {
    return 0;
  }
#endif //STUB_ContainerAccessProperty_get

#ifndef STUB_ContainerAccessProperty_set
//#define STUB_ContainerAccessProperty_set
  void ContainerAccessProperty::set(const Atlas::Message::Element&)
  {
    
  }
#endif //STUB_ContainerAccessProperty_set

#ifndef STUB_ContainerAccessProperty_copy
//#define STUB_ContainerAccessProperty_copy
  ContainerAccessProperty* ContainerAccessProperty::copy() const
  {
    return nullptr;
  }
#endif //STUB_ContainerAccessProperty_copy

#ifndef STUB_ContainerAccessProperty_operation
//#define STUB_ContainerAccessProperty_operation
  HandlerResult ContainerAccessProperty::operation(LocatedEntity& e, const Operation& op, OpVector& res)
  {
    return *static_cast<HandlerResult*>(nullptr);
  }
#endif //STUB_ContainerAccessProperty_operation

#ifndef STUB_ContainerAccessProperty_install
//#define STUB_ContainerAccessProperty_install
  void ContainerAccessProperty::install(LocatedEntity&, const std::string&)
  {
    
  }
#endif //STUB_ContainerAccessProperty_install

#ifndef STUB_ContainerAccessProperty_remove
//#define STUB_ContainerAccessProperty_remove
  void ContainerAccessProperty::remove(LocatedEntity&, const std::string& name)
  {
    
  }
#endif //STUB_ContainerAccessProperty_remove


#endif