// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubOgreMeshDeserializer_custom.h file.

#ifndef STUB_RULES_SIMULATION_OGREMESHDESERIALIZER_H
#define STUB_RULES_SIMULATION_OGREMESHDESERIALIZER_H

#include "rules/simulation/OgreMeshDeserializer.h"
#include "stubOgreMeshDeserializer_custom.h"

#ifndef STUB_OgreMeshDeserializer_OgreMeshDeserializer
//#define STUB_OgreMeshDeserializer_OgreMeshDeserializer
   OgreMeshDeserializer::OgreMeshDeserializer(std::ifstream& stream)
  {
    
  }
#endif //STUB_OgreMeshDeserializer_OgreMeshDeserializer

#ifndef STUB_OgreMeshDeserializer_deserialize
//#define STUB_OgreMeshDeserializer_deserialize
  void OgreMeshDeserializer::deserialize()
  {
    
  }
#endif //STUB_OgreMeshDeserializer_deserialize

#ifndef STUB_OgreMeshDeserializer_determineEndianness
//#define STUB_OgreMeshDeserializer_determineEndianness
  void OgreMeshDeserializer::determineEndianness(std::istream& stream)
  {
    
  }
#endif //STUB_OgreMeshDeserializer_determineEndianness

#ifndef STUB_OgreMeshDeserializer_readFileHeader
//#define STUB_OgreMeshDeserializer_readFileHeader
  void OgreMeshDeserializer::readFileHeader(std::istream& stream)
  {
    
  }
#endif //STUB_OgreMeshDeserializer_readFileHeader

#ifndef STUB_OgreMeshDeserializer_readChunk
//#define STUB_OgreMeshDeserializer_readChunk
  unsigned short OgreMeshDeserializer::readChunk(std::istream& stream)
  {
    return 0;
  }
#endif //STUB_OgreMeshDeserializer_readChunk

#ifndef STUB_OgreMeshDeserializer_readBools
//#define STUB_OgreMeshDeserializer_readBools
  void OgreMeshDeserializer::readBools(std::istream& stream, bool* pDest, size_t count)
  {
    
  }
#endif //STUB_OgreMeshDeserializer_readBools

#ifndef STUB_OgreMeshDeserializer_readFloats
//#define STUB_OgreMeshDeserializer_readFloats
  void OgreMeshDeserializer::readFloats(std::istream& stream, float* pDest, size_t count)
  {
    
  }
#endif //STUB_OgreMeshDeserializer_readFloats

#ifndef STUB_OgreMeshDeserializer_readShorts
//#define STUB_OgreMeshDeserializer_readShorts
  void OgreMeshDeserializer::readShorts(std::istream& stream, unsigned short* pDest, size_t count)
  {
    
  }
#endif //STUB_OgreMeshDeserializer_readShorts

#ifndef STUB_OgreMeshDeserializer_readInts
//#define STUB_OgreMeshDeserializer_readInts
  void OgreMeshDeserializer::readInts(std::istream& stream, std::uint32_t* pDest, size_t count)
  {
    
  }
#endif //STUB_OgreMeshDeserializer_readInts

#ifndef STUB_OgreMeshDeserializer_readString
//#define STUB_OgreMeshDeserializer_readString
  std::string OgreMeshDeserializer::readString(std::istream& stream)
  {
    return "";
  }
#endif //STUB_OgreMeshDeserializer_readString

#ifndef STUB_OgreMeshDeserializer_flipFromLittleEndian
//#define STUB_OgreMeshDeserializer_flipFromLittleEndian
  void OgreMeshDeserializer::flipFromLittleEndian(void* pData, size_t size, size_t count)
  {
    
  }
#endif //STUB_OgreMeshDeserializer_flipFromLittleEndian

#ifndef STUB_OgreMeshDeserializer_calcChunkHeaderSize
//#define STUB_OgreMeshDeserializer_calcChunkHeaderSize
  size_t OgreMeshDeserializer::calcChunkHeaderSize()
  {
    return 0;
  }
#endif //STUB_OgreMeshDeserializer_calcChunkHeaderSize

#ifndef STUB_OgreMeshDeserializer_backpedalChunkHeader
//#define STUB_OgreMeshDeserializer_backpedalChunkHeader
  void OgreMeshDeserializer::backpedalChunkHeader(std::istream& stream)
  {
    
  }
#endif //STUB_OgreMeshDeserializer_backpedalChunkHeader

#ifndef STUB_OgreMeshDeserializer_skipChunk
//#define STUB_OgreMeshDeserializer_skipChunk
  void OgreMeshDeserializer::skipChunk(std::istream& stream)
  {
    
  }
#endif //STUB_OgreMeshDeserializer_skipChunk

#ifndef STUB_OgreMeshDeserializer_readMesh
//#define STUB_OgreMeshDeserializer_readMesh
  void OgreMeshDeserializer::readMesh()
  {
    
  }
#endif //STUB_OgreMeshDeserializer_readMesh

#ifndef STUB_OgreMeshDeserializer_readSubMesh
//#define STUB_OgreMeshDeserializer_readSubMesh
  void OgreMeshDeserializer::readSubMesh()
  {
    
  }
#endif //STUB_OgreMeshDeserializer_readSubMesh

#ifndef STUB_OgreMeshDeserializer_readGeometry
//#define STUB_OgreMeshDeserializer_readGeometry
  void OgreMeshDeserializer::readGeometry()
  {
    
  }
#endif //STUB_OgreMeshDeserializer_readGeometry

#ifndef STUB_OgreMeshDeserializer_readGeometryVertexDeclaration
//#define STUB_OgreMeshDeserializer_readGeometryVertexDeclaration
  std::vector<OgreMeshDeserializer::VertexElement> OgreMeshDeserializer::readGeometryVertexDeclaration()
  {
    return std::vector<OgreMeshDeserializer::VertexElement>();
  }
#endif //STUB_OgreMeshDeserializer_readGeometryVertexDeclaration

#ifndef STUB_OgreMeshDeserializer_readGeometryVertexElement
//#define STUB_OgreMeshDeserializer_readGeometryVertexElement
  OgreMeshDeserializer::VertexElement OgreMeshDeserializer::readGeometryVertexElement()
  {
    return *static_cast<OgreMeshDeserializer::VertexElement*>(nullptr);
  }
#endif //STUB_OgreMeshDeserializer_readGeometryVertexElement

#ifndef STUB_OgreMeshDeserializer_readGeometryVertexBuffer
//#define STUB_OgreMeshDeserializer_readGeometryVertexBuffer
  std::vector<char> OgreMeshDeserializer::readGeometryVertexBuffer(unsigned int vertexCount)
  {
    return std::vector<char>();
  }
#endif //STUB_OgreMeshDeserializer_readGeometryVertexBuffer

#ifndef STUB_OgreMeshDeserializer_readBoundsInfo
//#define STUB_OgreMeshDeserializer_readBoundsInfo
  void OgreMeshDeserializer::readBoundsInfo()
  {
    
  }
#endif //STUB_OgreMeshDeserializer_readBoundsInfo


#endif