// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubSquallHandler_custom.h file.

#ifndef STUB_COMMON_NET_SQUALLHANDLER_H
#define STUB_COMMON_NET_SQUALLHANDLER_H

#include "common/net/SquallHandler.h"
#include "stubSquallHandler_custom.h"

#endif