// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubAstronomy_custom.h file.

#include "rulesets/astronomy/Astronomy.h"
#include "stubAstronomy_custom.h"

#ifndef STUB_RULESETS_ASTRONOMY_ASTRONOMY_H
#define STUB_RULESETS_ASTRONOMY_ASTRONOMY_H


#endif