// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubWorld_custom.h file.

#include "rulesets/astronomy/World.h"
#include "stubWorld_custom.h"

#ifndef STUB_RULESETS_ASTRONOMY_WORLD_H
#define STUB_RULESETS_ASTRONOMY_WORLD_H


#endif