// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubParserDefinitions_custom.h file.

#include "rulesets/entityfilter/ParserDefinitions.h"
#include "stubParserDefinitions_custom.h"

#ifndef STUB_RULESETS_ENTITYFILTER_PARSERDEFINITIONS_H
#define STUB_RULESETS_ENTITYFILTER_PARSERDEFINITIONS_H

#endif