// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubShape_impl_custom.h file.

#include "physics/Shape_impl.h"
#include "stubShape_impl_custom.h"

#ifndef STUB_PHYSICS_SHAPE_IMPL_H
#define STUB_PHYSICS_SHAPE_IMPL_H

#endif