// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubBBox_custom.h file.

#include "physics/BBox.h"
#include "stubBBox_custom.h"

#ifndef STUB_PHYSICS_BBOX_H
#define STUB_PHYSICS_BBOX_H

#endif