// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubTransform_custom.h file.

#include "physics/Transform.h"
#include "stubTransform_custom.h"

#ifndef STUB_PHYSICS_TRANSFORM_H
#define STUB_PHYSICS_TRANSFORM_H

#ifndef STUB_Transform_get
//#define STUB_Transform_get
  int Transform::get(Atlas::Message::MapType &) const
  {
    return 0;
  }
#endif //STUB_Transform_get

#ifndef STUB_Transform_set
//#define STUB_Transform_set
  void Transform::set(const Atlas::Message::Element &)
  {
    
  }
#endif //STUB_Transform_set


#endif