# This map should be auto generated by the create_map.py function!
# Do not edit by hand.

#world = { "house":("world.object.building.House", "House")}

object_class_list   = [
                        "world.objects.Thing",
                        "world.objects.buildings.House",
                        "world.objects.buildings.StoneHouse",
                        "world.objects.buildings.Sty",
                        "world.objects.Character",
                        "world.objects.Thing",
                        "world.objects.characters.Creator",
                        "world.objects.characters.Farmer",
                        "world.objects.characters.Butcher",
                        "world.objects.characters.Merchant",
                        "world.objects.characters.Smith",
                        "world.objects.characters.Guard",
                        "world.objects.food.Vodka",
                        "world.objects.food.Ham",
                        "world.objects.tools.Axe",
                        "world.objects.tools.Sword",
                        "world.objects.tools.Cleaver",
                        "world.objects.tools.Coin",
                        "world.objects.materials.Lumber",
                        "world.objects.buildings.House",
                        "world.objects.elements.Fire",
                        "world.objects.plants.Tree",
                        "world.objects.plants.Oak",
                        "world.objects.plants.seeds.Seed",
                        "world.objects.plants.seeds.Acorn",
                        "world.objects.animals.Animal",
                        "world.objects.animals.Pig",
                        "world.objects.animals.Wolf",
                        "world.objects.animals.Crab",
                        "world.objects.animals.Squirrel",
                        "world.objects.undead.Undead",
                        "world.objects.undead.Skeleton",
                        "world.objects.undead.Skull",
                        "world.objects.undead.Ribcage",
                        "world.objects.undead.Arm",
                        "world.objects.undead.Pelvis",
                        "world.objects.undead.Thigh",
                        "world.objects.undead.Shin",
                        "world.objects.undead.Lych",
                        "world.objects.outdoor.Campfire",
                        "world.objects.Weather"
                      ]

mind_class_list     = [
                         "mind.goals.common.common",
                         "mind.goals.common.misc_goal",
                         "mind.goals.common.move",
                         "mind.goals.humanoid.build_home",
                         "mind.goals.humanoid.fire",
                         "mind.goal.common.move"
                      ]

