// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubIHeightProvider_custom.h file.

#include "navigation/IHeightProvider.h"
#include "stubIHeightProvider_custom.h"

#ifndef STUB_NAVIGATION_IHEIGHTPROVIDER_H
#define STUB_NAVIGATION_IHEIGHTPROVIDER_H

#ifndef STUB_IHeightProvider_blitHeights
//#define STUB_IHeightProvider_blitHeights
  void IHeightProvider::blitHeights(int xMin, int xMax, int yMin, int yMax, std::vector<float>& heights) const
  {
    
  }
#endif //STUB_IHeightProvider_blitHeights


#endif