// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubfastlz_custom.h file.

#ifndef STUB_NAVIGATION_FASTLZ_H
#define STUB_NAVIGATION_FASTLZ_H

#include "navigation/fastlz.h"
#include "stubfastlz_custom.h"

#endif