// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubAdd_custom.h file.

#ifndef STUB_COMMON_OPERATIONS_ADD_H
#define STUB_COMMON_OPERATIONS_ADD_H

#include "common/operations/Add.h"
#include "stubAdd_custom.h"

namespace Atlas {
namespace Objects {
namespace Operation {


}  // namespace Operation
}  // namespace Objects
}  // namespace Atlas

#endif