// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubThought_custom.h file.

#ifndef STUB_COMMON_OPERATIONS_THOUGHT_H
#define STUB_COMMON_OPERATIONS_THOUGHT_H

#include "common/operations/Thought.h"
#include "stubThought_custom.h"

namespace Atlas {
namespace Objects {
namespace Operation {


}  // namespace Operation
}  // namespace Objects
}  // namespace Atlas

#endif