// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCloseContainer_custom.h file.

#ifndef STUB_COMMON_OPERATIONS_CLOSECONTAINER_H
#define STUB_COMMON_OPERATIONS_CLOSECONTAINER_H

#include "common/operations/CloseContainer.h"
#include "stubCloseContainer_custom.h"

namespace Atlas {
namespace Objects {
namespace Operation {


}  // namespace Operation
}  // namespace Objects
}  // namespace Atlas

#endif