// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubObserverClient_custom.h file.

#ifndef STUB_CLIENT_CYCLIENT_OBSERVERCLIENT_H
#define STUB_CLIENT_CYCLIENT_OBSERVERCLIENT_H

#include "client/cyclient/ObserverClient.h"
#include "stubObserverClient_custom.h"

#ifndef STUB_ObserverClient_ObserverClient
//#define STUB_ObserverClient_ObserverClient
   ObserverClient::ObserverClient(boost::asio::io_context& io_context, Atlas::Objects::Factories& factories, TypeStore& typeStore)
    : BaseClient(io_context, factories, typeStore)
  {
    
  }
#endif //STUB_ObserverClient_ObserverClient

#ifndef STUB_ObserverClient_ObserverClient_DTOR
//#define STUB_ObserverClient_ObserverClient_DTOR
   ObserverClient::~ObserverClient()
  {
    
  }
#endif //STUB_ObserverClient_ObserverClient_DTOR

#ifndef STUB_ObserverClient_setup
//#define STUB_ObserverClient_setup
  int ObserverClient::setup(const std::string & account , const std::string & password , const std::string & avatar )
  {
    return 0;
  }
#endif //STUB_ObserverClient_setup

#ifndef STUB_ObserverClient_teardown
//#define STUB_ObserverClient_teardown
  int ObserverClient::teardown()
  {
    return 0;
  }
#endif //STUB_ObserverClient_teardown

#ifndef STUB_ObserverClient_idle
//#define STUB_ObserverClient_idle
  void ObserverClient::idle()
  {
    
  }
#endif //STUB_ObserverClient_idle


#endif