// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCyPy_CreatorClient_custom.h file.

#ifndef STUB_CLIENT_CYCLIENT_CYPY_CREATORCLIENT_H
#define STUB_CLIENT_CYCLIENT_CYPY_CREATORCLIENT_H

#include "client/cyclient/CyPy_CreatorClient.h"
#include "stubCyPy_CreatorClient_custom.h"

#ifndef STUB_CyPy_CreatorClient_CyPy_CreatorClient
//#define STUB_CyPy_CreatorClient_CyPy_CreatorClient
   CyPy_CreatorClient::CyPy_CreatorClient(Py::PythonClassInstance* self, Py::Tuple& args, Py::Dict& kwds)
    : WrapperBase(self, args, kwds)
  {
    
  }
#endif //STUB_CyPy_CreatorClient_CyPy_CreatorClient

#ifndef STUB_CyPy_CreatorClient_CyPy_CreatorClient
//#define STUB_CyPy_CreatorClient_CyPy_CreatorClient
   CyPy_CreatorClient::CyPy_CreatorClient(Py::PythonClassInstance* self, Ref<CreatorClient> value)
    : WrapperBase(self, value)
  {
    
  }
#endif //STUB_CyPy_CreatorClient_CyPy_CreatorClient

#ifndef STUB_CyPy_CreatorClient_CyPy_CreatorClient_DTOR
//#define STUB_CyPy_CreatorClient_CyPy_CreatorClient_DTOR
   CyPy_CreatorClient::~CyPy_CreatorClient()
  {
    
  }
#endif //STUB_CyPy_CreatorClient_CyPy_CreatorClient_DTOR

#ifndef STUB_CyPy_CreatorClient_init_type
//#define STUB_CyPy_CreatorClient_init_type
   void CyPy_CreatorClient::init_type()
  {
    
  }
#endif //STUB_CyPy_CreatorClient_init_type

#ifndef STUB_CyPy_CreatorClient_getattro
//#define STUB_CyPy_CreatorClient_getattro
  Py::Object CyPy_CreatorClient::getattro(const Py::String& name)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_CreatorClient_getattro

#ifndef STUB_CyPy_CreatorClient_setattro
//#define STUB_CyPy_CreatorClient_setattro
  int CyPy_CreatorClient::setattro(const Py::String& name, const Py::Object& attr)
  {
    return 0;
  }
#endif //STUB_CyPy_CreatorClient_setattro

#ifndef STUB_CyPy_CreatorClient_make
//#define STUB_CyPy_CreatorClient_make
  Py::Object CyPy_CreatorClient::make(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_CreatorClient_make

#ifndef STUB_CyPy_CreatorClient_as_entity
//#define STUB_CyPy_CreatorClient_as_entity
  Py::Object CyPy_CreatorClient::as_entity()
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_CreatorClient_as_entity

#ifndef STUB_CyPy_CreatorClient_set
//#define STUB_CyPy_CreatorClient_set
  Py::Object CyPy_CreatorClient::set(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_CreatorClient_set

#ifndef STUB_CyPy_CreatorClient_look
//#define STUB_CyPy_CreatorClient_look
  Py::Object CyPy_CreatorClient::look(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_CreatorClient_look

#ifndef STUB_CyPy_CreatorClient_look_for
//#define STUB_CyPy_CreatorClient_look_for
  Py::Object CyPy_CreatorClient::look_for(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_CreatorClient_look_for

#ifndef STUB_CyPy_CreatorClient_send
//#define STUB_CyPy_CreatorClient_send
  Py::Object CyPy_CreatorClient::send(const Py::Tuple& argsp)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_CreatorClient_send

#ifndef STUB_CyPy_CreatorClient_delete_
//#define STUB_CyPy_CreatorClient_delete_
  Py::Object CyPy_CreatorClient::delete_(const Py::Tuple& args)
  {
    return *static_cast<Py::Object*>(nullptr);
  }
#endif //STUB_CyPy_CreatorClient_delete_


#endif