// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubCreatorClient_custom.h file.

#ifndef STUB_CLIENT_CYCLIENT_CREATORCLIENT_H
#define STUB_CLIENT_CYCLIENT_CREATORCLIENT_H

#include "client/cyclient/CreatorClient.h"
#include "stubCreatorClient_custom.h"

#ifndef STUB_CreatorClient_CreatorClient
//#define STUB_CreatorClient_CreatorClient
   CreatorClient::CreatorClient(RouterId mindId, const std::string& entityId, ClientConnection&, TypeStore& typeStore)
    : CharacterClient(mindId, entityId, ClientConnection, typeStore)
  {
    
  }
#endif //STUB_CreatorClient_CreatorClient

#ifndef STUB_CreatorClient_handleMakeResponse
//#define STUB_CreatorClient_handleMakeResponse
  LocatedEntity* CreatorClient::handleMakeResponse(const Atlas::Objects::Operation::RootOperation&, double)
  {
    return nullptr;
  }
#endif //STUB_CreatorClient_handleMakeResponse

#ifndef STUB_CreatorClient_make
//#define STUB_CreatorClient_make
  Ref<LocatedEntity> CreatorClient::make(const Atlas::Objects::Entity::RootEntity&)
  {
    return *static_cast<Ref<LocatedEntity>*>(nullptr);
  }
#endif //STUB_CreatorClient_make

#ifndef STUB_CreatorClient_sendSet
//#define STUB_CreatorClient_sendSet
  void CreatorClient::sendSet(const std::string&, const Atlas::Objects::Entity::RootEntity&)
  {
    
  }
#endif //STUB_CreatorClient_sendSet

#ifndef STUB_CreatorClient_del
//#define STUB_CreatorClient_del
  void CreatorClient::del(const std::string&)
  {
    
  }
#endif //STUB_CreatorClient_del


#endif