// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubMemEntity_custom.h file.

#ifndef STUB_RULES_AI_MEMENTITY_H
#define STUB_RULES_AI_MEMENTITY_H

#include "rules/ai/MemEntity.h"
#include "stubMemEntity_custom.h"

#ifndef STUB_MemEntity_createProperty
//#define STUB_MemEntity_createProperty
  std::unique_ptr<PropertyBase> MemEntity::createProperty(const std::string& propertyName) const
  {
    return *static_cast<std::unique_ptr<PropertyBase>*>(nullptr);
  }
#endif //STUB_MemEntity_createProperty

#ifndef STUB_MemEntity_MemEntity
//#define STUB_MemEntity_MemEntity
   MemEntity::MemEntity(RouterId id)
    : LocatedEntity(id)
  {
    
  }
#endif //STUB_MemEntity_MemEntity

#ifndef STUB_MemEntity_externalOperation
//#define STUB_MemEntity_externalOperation
  void MemEntity::externalOperation(const Operation& op, Link&)
  {
    
  }
#endif //STUB_MemEntity_externalOperation

#ifndef STUB_MemEntity_operation
//#define STUB_MemEntity_operation
  void MemEntity::operation(const Operation&, OpVector&)
  {
    
  }
#endif //STUB_MemEntity_operation

#ifndef STUB_MemEntity_destroy
//#define STUB_MemEntity_destroy
  void MemEntity::destroy()
  {
    
  }
#endif //STUB_MemEntity_destroy


#endif