// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubAwarenessStoreProvider_custom.h file.

#ifndef STUB_RULES_AI_AWARENESSSTOREPROVIDER_H
#define STUB_RULES_AI_AWARENESSSTOREPROVIDER_H

#include "rules/ai/AwarenessStoreProvider.h"
#include "stubAwarenessStoreProvider_custom.h"

#ifndef STUB_AwarenessStoreProvider_AwarenessStoreProvider
//#define STUB_AwarenessStoreProvider_AwarenessStoreProvider
   AwarenessStoreProvider::AwarenessStoreProvider(IHeightProvider& heightProvider)
  {
    
  }
#endif //STUB_AwarenessStoreProvider_AwarenessStoreProvider

#ifndef STUB_AwarenessStoreProvider_getStore
//#define STUB_AwarenessStoreProvider_getStore
  AwarenessStore& AwarenessStoreProvider::getStore(const TypeNode* type, int tileSize )
  {
    return *static_cast<AwarenessStore*>(nullptr);
  }
#endif //STUB_AwarenessStoreProvider_getStore


#endif