// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubSkill_custom.h file.

#ifndef STUB_RULES_SKILLS_SKILL_H
#define STUB_RULES_SKILLS_SKILL_H

#include "rules/skills/Skill.h"
#include "stubSkill_custom.h"

#ifndef STUB_Skill_action
//#define STUB_Skill_action
  oplist Skill::action(const std::string & skill, const Atlas::Objects::Operation::RootOperation & op)
  {
    return *static_cast<oplist*>(nullptr);
  }
#endif //STUB_Skill_action


#endif