// AUTOGENERATED file, created by the tool generate_stub.py, don't edit!
// If you want to add your own functionality, instead edit the stubAiClientPropertyManager_custom.h file.

#ifndef STUB_CLIENT_AICLIENT_AICLIENTPROPERTYMANAGER_H
#define STUB_CLIENT_AICLIENT_AICLIENTPROPERTYMANAGER_H

#include "client/aiclient/AiClientPropertyManager.h"
#include "stubAiClientPropertyManager_custom.h"

#ifndef STUB_AiClientPropertyManager_AiClientPropertyManager
//#define STUB_AiClientPropertyManager_AiClientPropertyManager
   AiClientPropertyManager::AiClientPropertyManager()
    : PropertyManager()
  {
    
  }
#endif //STUB_AiClientPropertyManager_AiClientPropertyManager

#ifndef STUB_AiClientPropertyManager_addProperty
//#define STUB_AiClientPropertyManager_addProperty
  std::unique_ptr<PropertyBase> AiClientPropertyManager::addProperty(const std::string& name, int type)
  {
    return *static_cast<std::unique_ptr<PropertyBase>*>(nullptr);
  }
#endif //STUB_AiClientPropertyManager_addProperty


#endif